begin;
do $$
declare host uuid; ids uuid[]; e uuid; room uuid; layout jsonb := '{}'; invalid jsonb; denied boolean; i integer; snapshot jsonb; seat_before integer;
begin
 select user_id into host from public.site_roles where role='MAIN_ADMIN' limit 1;
 select array_agg(id) into ids from (select id from public.profiles where id<>host order by id limit 6) x;
 if cardinality(ids)<6 then raise exception 'Need fixture profiles'; end if;
 perform set_config('request.jwt.claim.sub',host::text,true);
 insert into public.events(title,event_kind,created_by,started_at,event_status,max_participants) values('Clocktower layout rollback test','CLOCKTOWER',host,now()+interval '2 days','OPEN',16) returning id into e;
 for i in 1..5 loop
  insert into public.event_participants(event_id,user_id) values(e,ids[i]);
  layout:=layout || jsonb_build_object(ids[i]::text,jsonb_build_object('x',100*i,'y',100+i*50));
 end loop;
 perform public.clocktower_live_command(e,'create','{}');
 select id into room from public.clocktower_live_rooms where event_id=e;
 select seat into seat_before from public.clocktower_live_members where room_id=room and user_id=ids[1];
 perform public.clocktower_save_layout(e,room,0,layout);
 if not exists(select 1 from public.clocktower_live_rooms where id=room and seating_layout=layout and seating_revision=1) then raise exception 'Layout not persisted'; end if;
 if not exists(select 1 from public.clocktower_live_members where room_id=room and user_id=ids[1] and seat=seat_before and actual_role='') then raise exception 'Layout changed game order or role'; end if;
 denied:=false;
 begin perform public.clocktower_save_layout(e,room,0,layout); exception when others then denied:=true; end;
 if not denied then raise exception 'Stale revision allowed'; end if;
 denied:=false;
 begin perform public.clocktower_save_layout(e,null,1,layout); exception when others then denied:=true; end;
 if not denied then raise exception 'Null room allowed'; end if;
 denied:=false;
 begin perform public.clocktower_save_layout(e,room,1,layout-ids[1]::text); exception when others then denied:=true; end;
 if not denied then raise exception 'Missing participant allowed'; end if;
 invalid:=(layout-ids[1]::text)||jsonb_build_object(ids[6]::text,jsonb_build_object('x',100,'y',100));
 denied:=false;
 begin perform public.clocktower_save_layout(e,room,1,invalid); exception when others then denied:=true; end;
 if not denied then raise exception 'Foreign participant allowed'; end if;
 invalid:=jsonb_set(layout,array[ids[1]::text,'x'],'1001');
 denied:=false;
 begin perform public.clocktower_save_layout(e,room,1,invalid); exception when others then denied:=true; end;
 if not denied then raise exception 'Out of bounds allowed'; end if;
 invalid:=jsonb_set(layout,array[ids[1]::text,'notes'],'"SECRET"');
 denied:=false;
 begin perform public.clocktower_save_layout(e,room,1,invalid); exception when others then denied:=true; end;
 if not denied then raise exception 'Non-coordinate data allowed'; end if;
 perform set_config('request.jwt.claim.sub',ids[1]::text,true);
 snapshot:=public.clocktower_live_snapshot(e);
 if snapshot->'room'->'seating_layout'<>layout or snapshot::text like '%actual_role%' or snapshot::text like '%shown_role%' then raise exception 'Shared layout or masking incorrect'; end if;
 denied:=false;
 begin perform public.clocktower_save_layout(e,room,1,layout); exception when others then denied:=true; end;
 if not denied then raise exception 'Player saved layout'; end if;
 perform set_config('request.jwt.claim.sub',ids[6]::text,true);
 if public.clocktower_live_snapshot(e)::text like '%seating_layout%' then raise exception 'Nonparticipant saw layout'; end if;
 perform set_config('request.jwt.claim.sub',host::text,true);
 update public.clocktower_live_rooms set phase='NIGHT',night=1 where id=room;
 denied:=false;
 begin perform public.clocktower_save_layout(e,room,1,layout); exception when others then denied:=true; end;
 if not denied then raise exception 'Night layout changed'; end if;
 if has_function_privilege('anon','public.clocktower_save_layout(uuid,uuid,integer,jsonb)','EXECUTE') then raise exception 'Anonymous access granted'; end if;
end $$;
rollback;
