begin;
do $$
declare host uuid; ids uuid[]; e uuid; room uuid; request uuid; payload jsonb; denied boolean; i integer;
begin
 select user_id into host from public.site_roles where role='MAIN_ADMIN' limit 1;
 select array_agg(id) into ids from (select id from public.profiles where id<>host order by id limit 6) x;
 if cardinality(ids)<6 then raise exception 'Need fixture profiles'; end if;
 perform set_config('request.jwt.claim.sub',host::text,true);
 insert into public.events(title,event_kind,created_by,started_at,event_status,max_participants) values('Clocktower rollback test','CLOCKTOWER',host,now()+interval '2 days','OPEN',16) returning id into e;
 for i in 1..5 loop insert into public.event_participants(event_id,user_id) values(e,ids[i]); end loop;
 perform public.clocktower_live_command(e,'create','{}');
 select id into room from public.clocktower_live_rooms where event_id=e;
 for i in 1..5 loop
  perform public.clocktower_live_command(e,'member',jsonb_build_object('room_id',room,'user_id',ids[i],'seat',i,'actual_role',(array['주정뱅이','임프','수도사','점쟁이','집사'])[i],'shown_role',(array['요리사','임프','수도사','점쟁이','집사'])[i],'notes','SECRET_TEST'));
 end loop;
 perform set_config('request.jwt.claim.sub',ids[1]::text,true);
 payload:=public.clocktower_live_snapshot(e);
 if payload::text like '%SECRET_TEST%' or payload::text like '%shown_role%' or payload::text like '%actual_role%' then raise exception 'Setup secrets leaked'; end if;
 denied:=false; begin perform public.clocktower_live_command(e,'phase',jsonb_build_object('room_id',room,'phase','NIGHT')); exception when others then denied:=true; end;
 if not denied then raise exception 'Player advanced phase'; end if;
 perform set_config('request.jwt.claim.sub',host::text,true);
 perform public.clocktower_live_command(e,'phase',jsonb_build_object('room_id',room,'phase','NIGHT'));
 perform set_config('request.jwt.claim.sub',ids[1]::text,true);
 payload:=public.clocktower_live_snapshot(e);
 if payload::text like '%주정뱅이%' or payload::text like '%임프%' or payload::text like '%SECRET_TEST%' or payload::text not like '%요리사%' then raise exception 'Player role masking failed'; end if;
 perform set_config('request.jwt.claim.sub',ids[6]::text,true);
 payload:=public.clocktower_live_snapshot(e);
 if payload->'room'<>'null'::jsonb or payload ? 'members' then raise exception 'Outsider viewed room'; end if;
 perform set_config('request.jwt.claim.sub',host::text,true);
 perform public.clocktower_live_command(e,'request',jsonb_build_object('room_id',room,'night',1,'user_id',ids[3],'prompt','Choose','target_count',1,'allow_self',false));
 select id into request from public.clocktower_live_requests where room_id=room;
 perform set_config('request.jwt.claim.sub',ids[4]::text,true);
 if jsonb_array_length(public.clocktower_live_snapshot(e)->'requests')<>0 then raise exception 'Other player request leaked'; end if;
 denied:=false; begin perform public.clocktower_live_command(e,'reply',jsonb_build_object('room_id',room,'request_id',request,'targets',jsonb_build_array(ids[2]))); exception when others then denied:=true; end;
 if not denied then raise exception 'Other player submitted'; end if;
 perform set_config('request.jwt.claim.sub',ids[3]::text,true);
 denied:=false; begin perform public.clocktower_live_command(e,'reply',jsonb_build_object('room_id',room,'request_id',request,'targets',jsonb_build_array(ids[3]))); exception when others then denied:=true; end;
 if not denied then raise exception 'Self targeting allowed'; end if;
 perform public.clocktower_live_command(e,'reply',jsonb_build_object('room_id',room,'request_id',request,'targets',jsonb_build_array(ids[2])));
 denied:=false; begin perform public.clocktower_live_command(e,'reply',jsonb_build_object('room_id',room,'request_id',request,'targets',jsonb_build_array(ids[1]))); exception when others then denied:=true; end;
 if not denied then raise exception 'Duplicate submission allowed'; end if;
 perform set_config('request.jwt.claim.sub',host::text,true);
 denied:=false; begin perform public.clocktower_live_command(e,'phase',jsonb_build_object('room_id',room,'phase','DAY')); exception when others then denied:=true; end;
 if not denied then raise exception 'Unresolved night finished'; end if;
 perform public.clocktower_live_command(e,'resolve',jsonb_build_object('room_id',room,'request_id',request,'result','PRIVATE_RESULT'));
 perform set_config('request.jwt.claim.sub',ids[4]::text,true);
 if public.clocktower_live_snapshot(e)::text like '%PRIVATE_RESULT%' then raise exception 'Private result leaked'; end if;
 perform set_config('request.jwt.claim.sub',ids[3]::text,true);
 perform public.clocktower_live_command(e,'ack',jsonb_build_object('room_id',room,'request_id',request));
 perform set_config('request.jwt.claim.sub',host::text,true);
 update public.clocktower_live_members set alive=false where room_id=room and user_id=ids[2];
 perform set_config('request.jwt.claim.sub',ids[2]::text,true);
 if exists(select 1 from jsonb_array_elements(public.clocktower_live_snapshot(e)->'members') m where m->>'user_id'=ids[2]::text and m->>'alive'='false') then raise exception 'Night death leaked'; end if;
 perform set_config('request.jwt.claim.sub',host::text,true);
 perform public.clocktower_live_command(e,'phase',jsonb_build_object('room_id',room,'phase','DAY'));
 perform public.clocktower_live_command(e,'phase',jsonb_build_object('room_id',room,'phase','NIGHT'));
 denied:=false; begin perform public.clocktower_live_command(e,'request',jsonb_build_object('room_id',room,'night',1,'user_id',ids[1],'prompt','Stale','target_count',0)); exception when others then denied:=true; end;
 if not denied then raise exception 'Stale night allowed'; end if;
 perform public.clocktower_live_command(e,'request',jsonb_build_object('room_id',room,'night',2,'user_id',ids[1],'prompt','Info','target_count',0));
 select id into request from public.clocktower_live_requests where room_id=room and night=2;
 perform set_config('request.jwt.claim.sub',ids[1]::text,true);
 perform public.clocktower_live_command(e,'reply',jsonb_build_object('room_id',room,'request_id',request,'targets','[]'::jsonb));
 if not exists(select 1 from public.clocktower_live_requests where id=request and status='RESOLVED' and acknowledged) then raise exception 'Information acknowledgement failed'; end if;
 if has_table_privilege('authenticated','public.clocktower_live_members','SELECT') or has_table_privilege('anon','public.clocktower_live_requests','SELECT') then raise exception 'Direct access granted'; end if;
end $$;
rollback;
select 'PASS: setup masking, drunk masking, outsider denial, cross-user isolation, self-target validation, duplicate rejection, phase gating, result privacy, hidden night deaths, stale-night rejection, information acknowledgement, table grants; all fixtures rolled back' as result;
