-- Run as the database owner. All fixtures and helpers roll back, including on error.
begin;
create temporary table clocktower_test_context(eid uuid,rid uuid);
create function pg_temp.clocktower_test_action(action text, extra jsonb default '{}') returns void language plpgsql as $$
declare c record; r public.clocktower_live_rooms;
begin
 select * into c from clocktower_test_context;
 select * into r from public.clocktower_live_rooms where id=c.rid;
 perform public.clocktower_live_command(c.eid,action,jsonb_build_object('room_id',r.id,'version',r.engine_version,'state',r.night_engine)||extra);
end $$;
do $$
declare users uuid[]; eid uuid; rid uuid; info jsonb; engine jsonb; snap jsonb; qid uuid; old_version integer; blocked boolean; signature text;
begin
 select array_agg(id) into users from (select id from auth.users order by id limit 6) x;
 if cardinality(users)<6 then raise exception 'Six existing accounts are needed for this rollback-only test.';end if;
 select e.id into eid from public.events e where not exists(select 1 from public.clocktower_live_rooms r where r.event_id=e.id and r.phase<>'ENDED') order by e.id limit 1;
 if eid is null then raise exception 'No event without an active room is available.';end if;
 perform pg_advisory_xact_lock(hashtextextended(eid::text,0));
 insert into public.clocktower_live_rooms(event_id,storyteller_id) values(eid,users[1]) returning id into rid;
 insert into clocktower_test_context values(eid,rid);
 insert into public.clocktower_live_members(room_id,user_id,seat,actual_role,shown_role)
 select rid,users[i+1],i,role,role from unnest(array['점쟁이','초공감자','세탁부','독살범','임프']) with ordinality x(role,i);
 perform set_config('request.jwt.claim.sub',users[1]::text,true);
 select string_agg(user_id::text||':'||actual_role||':'||shown_role,'|' order by user_id::text collate "C") into signature from public.clocktower_live_members where room_id=rid;
 info:=jsonb_build_object('roster',signature,'bluffs',jsonb_build_array('사서','요리사','군인'),'registrations','{}'::jsonb,'clues',jsonb_build_object(users[4]::text,jsonb_build_object('role','점쟁이','correct',users[2],'decoy',users[3])));
 blocked:=false;
 begin perform pg_temp.clocktower_test_action('phase','{"phase":"NIGHT"}');exception when others then blocked:=true;end;
 assert blocked,'starting without preparation must fail';
 perform pg_temp.clocktower_test_action('engine_information',jsonb_build_object('state',jsonb_build_object('information',info,'red_herring',users[3])));
 blocked:=false;
 begin perform pg_temp.clocktower_test_action('engine_information',jsonb_build_object('state',jsonb_build_object('information',jsonb_set(info,'{bluffs}','["점쟁이","요리사","군인"]'),'red_herring',users[3])));exception when others then blocked:=true;end;
 assert blocked,'in-play bluff must fail';
 snap:=public.clocktower_live_snapshot(eid);assert snap->'engine'->'information'=info,'host sees saved settings';
 perform set_config('request.jwt.claim.sub',users[2]::text,true);
 snap:=public.clocktower_live_snapshot(eid);assert not(snap?'engine') and not(snap?'engine_version'),'player must not see private engine';
 assert not exists(select 1 from jsonb_array_elements(snap->'members') x where x?'actual_role' or x?'notes' or x?'shown_role'),'setup roles are secret';
 blocked:=false;begin perform pg_temp.clocktower_test_action('engine_settings');exception when others then blocked:=true;end;assert blocked,'non-host settings rejected';
 perform set_config('request.jwt.claim.sub',users[1]::text,true);
 perform pg_temp.clocktower_test_action('phase','{"phase":"NIGHT"}');
 engine:=jsonb_build_object('night',1,'cursor',0,'tasks',jsonb_build_array(jsonb_build_object('user_id',users[2],'role','점쟁이','key','ft')),'finished',false,'conditions','{}'::jsonb,'deaths','{}'::jsonb,'masters','{}'::jsonb,'information',info,'red_herring',users[3]);
 perform pg_temp.clocktower_test_action('engine_start',jsonb_build_object('state',engine));
 perform pg_temp.clocktower_test_action('engine_next',jsonb_build_object('request',jsonb_build_object('user_id',users[2],'target_count',2,'allow_self',true,'prompt','대상 2명 선택')));
 select (night_engine->>'active')::uuid,engine_version into qid,old_version from public.clocktower_live_rooms where id=rid;
 perform set_config('request.jwt.claim.sub',users[2]::text,true);
 perform pg_temp.clocktower_test_action('reply',jsonb_build_object('request_id',qid,'targets',jsonb_build_array(users[3],users[6])));
 perform set_config('request.jwt.claim.sub',users[1]::text,true);
 blocked:=false;begin perform pg_temp.clocktower_test_action('engine_approve',jsonb_build_object('version',old_version,'request_id',qid,'result','old'));exception when others then blocked:=true;end;assert blocked,'stale approval rejected';
 perform pg_temp.clocktower_test_action('engine_approve',jsonb_build_object('request_id',qid,'result','수정한 답안'));
 assert (select result='수정한 답안' and status='RESOLVED' from public.clocktower_live_requests where id=qid),'edited result persisted';
 blocked:=false;begin perform pg_temp.clocktower_test_action('engine_approve',jsonb_build_object('request_id',qid,'result','duplicate'));exception when others then blocked:=true;end;assert blocked,'duplicate approval rejected';
 select night_engine into engine from public.clocktower_live_rooms where id=rid;
 engine:=engine||'{"cursor":1,"finished":true}';
 blocked:=false;begin perform pg_temp.clocktower_test_action('engine_next',jsonb_build_object('state',engine));exception when others then blocked:=true;end;assert blocked,'next before acknowledgement rejected';
 perform set_config('request.jwt.claim.sub',users[2]::text,true);
 perform pg_temp.clocktower_test_action('ack',jsonb_build_object('request_id',qid));
 perform set_config('request.jwt.claim.sub',users[1]::text,true);
 perform pg_temp.clocktower_test_action('engine_next',jsonb_build_object('state',engine));
 update public.clocktower_live_missions set completed=true where room_id=rid;
 perform pg_temp.clocktower_test_action('phase','{"phase":"DAY"}');
 perform pg_temp.clocktower_test_action('phase','{"phase":"NIGHT"}');
 engine:=engine-'active'||jsonb_build_object('night',2,'cursor',0,'finished',false,'tasks',jsonb_build_array(jsonb_build_object('user_id',users[6],'role','임프','key','imp')));
 perform pg_temp.clocktower_test_action('engine_start',jsonb_build_object('state',engine));
 perform pg_temp.clocktower_test_action('engine_next',jsonb_build_object('request',jsonb_build_object('user_id',users[6],'target_count',1,'allow_self',true,'prompt','대상 선택')));
 select (night_engine->>'active')::uuid into qid from public.clocktower_live_rooms where id=rid;
 perform set_config('request.jwt.claim.sub',users[6]::text,true);
 perform pg_temp.clocktower_test_action('reply',jsonb_build_object('request_id',qid,'targets',jsonb_build_array(users[3])));
 perform set_config('request.jwt.claim.sub',users[1]::text,true);
 perform pg_temp.clocktower_test_action('engine_approve',jsonb_build_object('request_id',qid,'result','선택을 확인했습니다.','changes',jsonb_build_array(jsonb_build_object('user_id',users[3],'alive',false,'actual_role','초공감자','shown_role','초공감자'))));
 assert (select not alive and public_alive from public.clocktower_live_members where room_id=rid and user_id=users[3]),'night death remains private';
 perform set_config('request.jwt.claim.sub',users[2]::text,true);
 snap:=public.clocktower_live_snapshot(eid);
 assert not(snap?'engine'),'night engine hidden';
 assert (select (x->>'alive')::boolean from jsonb_array_elements(snap->'members') x where x->>'user_id'=users[3]::text),'player sees public life';
 assert not exists(select 1 from jsonb_array_elements(snap->'requests') x where x->>'user_id'<>users[2]::text),'other requests hidden';
 perform set_config('request.jwt.claim.sub',users[6]::text,true);
 perform pg_temp.clocktower_test_action('ack',jsonb_build_object('request_id',qid));
 perform set_config('request.jwt.claim.sub',users[1]::text,true);
 select night_engine||'{"cursor":1,"finished":true}' into engine from public.clocktower_live_rooms where id=rid;
 perform pg_temp.clocktower_test_action('engine_next',jsonb_build_object('state',engine));
 update public.clocktower_live_missions set completed=true where room_id=rid;
 perform pg_temp.clocktower_test_action('phase','{"phase":"DAY"}');
 assert (select not public_alive from public.clocktower_live_members where room_id=rid and user_id=users[3]),'dawn publishes death';
 assert not has_table_privilege('authenticated','public.clocktower_live_rooms','SELECT'),'private tables remain inaccessible';
 assert not has_function_privilege('authenticated','public.clocktower_live_command_v3(uuid,text,jsonb)','EXECUTE'),'legacy bypass inaccessible';
 assert not has_function_privilege('authenticated','public.clocktower_validate_information(uuid,jsonb,text)','EXECUTE'),'private validator inaccessible';
end $$;
rollback;
