const assert=require('node:assert/strict');const ts=require('typescript');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(require('fs').readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,f);
const {beginNight,emptyEngine,nextTask,propose,approveEffects,impaired}=require('../lib/clocktower/night.ts');
const make=(roles)=>roles.map((r,i)=>({user_id:String(i),seat:i+1,name:`P${i}`,alive:true,actual_role:r,shown_role:r}));
const task=(m)=>({user_id:m.user_id,role:m.shown_role,key:m.user_id});
let members=make(['독살범','수도사','첩자','임프','까마귀지기','장의사','초공감자','점쟁이','집사','세탁부','사서','수사관','요리사']);
let e=beginNight(undefined,1,members);
assert.deepEqual(e.tasks.map(t=>t.role),['하수인 정보','하수인 정보','악마 정보','독살범','첩자','세탁부','사서','수사관','요리사','초공감자','점쟁이','집사']);
for(const night of [2,3,4])assert.deepEqual(beginNight(undefined,night,members).tasks.map(t=>t.role),['독살범','수도사','첩자','임프','까마귀지기','장의사','초공감자','점쟁이','집사']);
e=beginNight(undefined,2,members);e.cursor=4;
assert.equal(nextTask(e,members).tasks[nextTask(e,members).cursor].role,'초공감자');
members[4].alive=false;e.deaths['4']={night:2,role:'까마귀지기'};
assert.equal(nextTask(e,members).tasks[nextTask(e,members).cursor].role,'까마귀지기');
members=make(['임프','초공감자','군인','독살범','점쟁이','수도사']);e=beginNight(undefined,2,members);e.red_herring='2';
assert.equal(propose(task(members[1]),[],e,members).result,'1');
members[2].alive=false;assert.equal(propose(task(members[1]),[],e,members).result,'2');
assert.equal(propose(task(members[4]),['2','3'],e,members).result,'악마가 있습니다.');
members[0].alive=false;assert.equal(propose(task(members[4]),['0','3'],e,members).result,'악마가 있습니다.');members[0].alive=true;members[2].alive=true;
e.poison={source:'3',target:'1',night:2};assert.ok(impaired(members[1],e,members));members[3].alive=false;assert.ok(!impaired(members[1],e,members));members[3].alive=true;
members[3].actual_role='임프';assert.ok(!impaired(members[1],e,members));members[3].actual_role='독살범';
e=beginNight(e,3,members);assert.equal(e.poison,undefined);
e.protection={source:'5',target:'0',night:3};assert.equal(propose(task(members[0]),['0'],e,members).victim,undefined);
e.protection=undefined;assert.equal(propose(task(members[0]),['2'],e,members).victim,undefined);
e.poison={source:'3',target:'2',night:3};assert.equal(propose(task(members[0]),['2'],e,members).victim,'2');
members=make(['임프','탕녀','독살범','초공감자','까마귀지기']);e=beginNight(undefined,2,members);let p=propose(task(members[0]),['0'],e,members);assert.equal(p.successor,'1');
let effects=approveEffects(task(members[0]),['0'],e,members,p);assert.equal(effects.changes.length,2);assert.equal(members[0].alive,true);assert.ok(effects.state.tasks.some(t=>t.role==='역할 변경'));
e.poison={source:'2',target:'1',night:2};p=propose(task(members[0]),['0'],e,members);assert.equal(p.successor,undefined);assert.ok(p.requiresChoice);
members=make(['임프','독살범','초공감자','까마귀지기','군인']);e=beginNight(undefined,2,members);p=propose(task(members[0]),['3'],e,members);effects=approveEffects(task(members[0]),['3'],e,members,p);assert.equal(effects.state.deaths['3'].role,'까마귀지기');
members=make(['임프','독살범','시장','초공감자','군인']);e=beginNight(undefined,2,members);assert.ok(propose(task(members[0]),['2'],e,members).requiresChoice);assert.equal(propose(task(members[0]),['2'],e,members,{victim:'4'}).victim,undefined);
members=make(['임프','독살범','점쟁이','수도사','장의사']);members[2].actual_role='주정뱅이';e=beginNight(undefined,2,members);e.red_herring='3';p=propose(task(members[2]),['0','1'],e,members);assert.equal(p.result,'악마가 없습니다.');assert.ok(p.reason.some(r=>r.includes('주정뱅이')));
console.log('Passed night order 1–4, death timing, Empath, Fortune Teller, Drunk, poison expiration, protection, Mayor, Ravenkeeper, Imp/Scarlet succession.');
