begin;
do $test$
declare r public.clocktower_live_rooms; m public.clocktower_live_missions; actor uuid; person uuid; request_id uuid; denied boolean; j jsonb; engine jsonb; i integer;
begin
 select * into r from public.clocktower_live_rooms where event_id='60cabf3d-9762-47fa-a1db-e4d55a548760' order by created_at desc,id desc limit 1;
 select user_id into actor from public.clocktower_live_members where room_id=r.id order by seat limit 1;
 select user_id into person from public.clocktower_live_members where room_id=r.id and user_id<>actor order by seat limit 1;
 if person is null then raise exception 'Populated room required';end if;
 update public.clocktower_live_rooms set phase='NIGHT',night=9991 where id=r.id returning * into r;
 engine:=r.night_engine;
 update public.clocktower_live_requests set status='CANCELLED' where room_id=r.id and status in ('OPEN','SUBMITTED');
 for i in 1..100 loop
  j:=public.clocktower_mission_challenge(case when i%2=0 then 'SELECT' else 'NOTICE' end);
  if (j->>'delay_seconds')::integer not between 1 and 5 or length(j->>'text')=0 then raise exception 'Invalid challenge';end if;
 end loop;
 perform public.clocktower_make_missions(r,1);
 if exists(select 1 from public.clocktower_live_missions where room_id=r.id and night=9991 and kind not in ('SELECT','NOTICE')) then raise exception 'Legacy generated';end if;
 update public.clocktower_live_missions set completed=true where room_id=r.id and night=9991;
 insert into public.clocktower_live_requests(room_id,user_id,night,prompt,target_count) values(r.id,actor,9991,'test',1) returning id into request_id;
 if not exists(select 1 from public.clocktower_live_missions where room_id=r.id and night=9991 and user_id=person and kind='SELECT' and not completed) then raise exception 'Selection cover missing';end if;
 update public.clocktower_live_missions set available_at=now()-interval '1 second' where room_id=r.id and night=9991;
 select * into m from public.clocktower_live_missions where room_id=r.id and night=9991 and user_id=person and not completed;
 perform set_config('request.jwt.claim.sub',actor::text,true);
 denied:=false;
 begin perform public.clocktower_live_command(r.event_id,'mission_complete',jsonb_build_object('room_id',r.id,'mission_id',m.id,'answer',actor));exception when others then denied:=true;end;
 if not denied then raise exception 'Other participant completed mission';end if;
 perform set_config('request.jwt.claim.sub',person::text,true);
 denied:=false;
 begin perform public.clocktower_live_command(r.event_id,'mission_complete',jsonb_build_object('room_id',r.id,'mission_id',m.id,'answer','invalid'));exception when others then denied:=true;end;
 if not denied then raise exception 'Invalid target accepted';end if;
 perform public.clocktower_live_command(r.event_id,'mission_complete',jsonb_build_object('room_id',r.id,'mission_id',m.id,'answer',actor));
 if not(select completed from public.clocktower_live_missions where id=m.id) then raise exception 'Selection failed';end if;
 update public.clocktower_live_requests set status='RESOLVED',result='test' where id=request_id;
 select * into m from public.clocktower_live_missions where room_id=r.id and night=9991 and user_id=person and not completed;
 if m.kind is distinct from 'NOTICE' then raise exception 'Notice cover missing';end if;
 update public.clocktower_live_missions set available_at=now()-interval '1 second' where id=m.id;
 perform public.clocktower_live_command(r.event_id,'mission_complete',jsonb_build_object('room_id',r.id,'mission_id',m.id,'answer','ACK'));
 if not(select completed from public.clocktower_live_missions where id=m.id) then raise exception 'Notice failed';end if;
 if (select night_engine from public.clocktower_live_rooms where id=r.id) is distinct from engine then raise exception 'Cover affected engine';end if;
 denied:=false;
 begin perform public.clocktower_save_mission_settings(array['test'],array['test']);exception when others then denied:=true;end;
 if not denied then raise exception 'Member could edit settings';end if;
 if has_table_privilege('authenticated','public.clocktower_mission_settings','UPDATE') then raise exception 'Direct settings write allowed';end if;
 perform set_config('request.jwt.claim.sub',r.storyteller_id::text,true);
 perform public.clocktower_save_mission_settings(array['테스트 질문'],array['테스트 안내']);
 if public.clocktower_mission_challenge('NOTICE')->>'text'<>'테스트 안내' then raise exception 'Settings not used';end if;
end $test$;
rollback;
select 'PASS: generation, cover selection/result triggers, ownership, completion, unchanged engine, admin settings' as result;
