begin;
create temporary table vote_test_context(eid uuid,rid uuid);
create function pg_temp.vote_action(action text,data jsonb default '{}') returns void language plpgsql as $$
declare c record;begin select * into c from vote_test_context;perform public.clocktower_live_command(c.eid,action,jsonb_build_object('room_id',c.rid)||data);end $$;
do $$
declare users uuid[]; eid uuid; rid uuid; vid uuid; snap jsonb; denied boolean; ordered uuid[];
begin
 select array_agg(id) into users from (select id from auth.users order by id limit 5) x;
 select e.id into eid from public.events e where not exists(select 1 from public.clocktower_live_rooms existing where existing.event_id=e.id and existing.phase<>'ENDED') limit 1;
 assert eid is not null and cardinality(users)=5;
 insert into public.clocktower_live_rooms(event_id,storyteller_id,phase,night) values(eid,users[1],'DAY',1) returning id into rid;
 insert into vote_test_context values(eid,rid);
 insert into public.clocktower_live_members(room_id,user_id,seat,actual_role,shown_role,alive,public_alive) values(rid,users[2],1,'임프','임프',true,true),(rid,users[3],2,'군인','군인',true,true),(rid,users[4],3,'요리사','요리사',false,false);
 perform set_config('request.jwt.claim.sub',users[2]::text,true);
 perform pg_temp.vote_action('vote_nominate',jsonb_build_object('nominee',users[2]));
 select id into vid from public.clocktower_live_votes where room_id=rid;
 denied:=false;begin perform pg_temp.vote_action('vote_start',jsonb_build_object('vote_id',vid));exception when others then denied:=true;end;assert denied,'only host starts';
 perform set_config('request.jwt.claim.sub',users[1]::text,true);
 perform pg_temp.vote_action('vote_start',jsonb_build_object('vote_id',vid));
 select voter_order into ordered from public.clocktower_live_votes where id=vid;assert ordered=array[users[3],users[4],users[2]],'clockwise, nominee last';
 denied:=false;begin perform pg_temp.vote_action('phase','{"phase":"NIGHT"}');exception when others then denied:=true;end;assert denied,'active vote blocks phase';
 perform set_config('request.jwt.claim.sub',users[3]::text,true);
 denied:=false;begin perform pg_temp.vote_action('vote_cast',jsonb_build_object('vote_id',vid,'yes',true));exception when others then denied:=true;end;assert denied,'early ballot rejected';
 update public.clocktower_live_votes set started_at=clock_timestamp()-interval '0.5 seconds' where id=vid;
 perform pg_temp.vote_action('vote_cast',jsonb_build_object('vote_id',vid,'yes',true));
 denied:=false;begin perform pg_temp.vote_action('vote_cast',jsonb_build_object('vote_id',vid,'yes',false));exception when others then denied:=true;end;assert denied,'duplicate ballot rejected';
 update public.clocktower_live_votes set started_at=clock_timestamp()-interval '3.5 seconds' where id=vid;
 denied:=false;begin perform pg_temp.vote_action('vote_cast',jsonb_build_object('vote_id',vid,'yes',true));exception when others then denied:=true;end;assert denied,'late ballot rejected';
 perform set_config('request.jwt.claim.sub',users[4]::text,true);perform pg_temp.vote_action('vote_cast',jsonb_build_object('vote_id',vid,'yes',true));
 assert (select ghost_vote_used from public.clocktower_live_members where room_id=rid and user_id=users[4]),'dead O consumes token';
 update public.clocktower_live_votes set started_at=clock_timestamp()-interval '20 seconds' where id=vid;
 snap:=public.clocktower_live_snapshot(eid);assert snap->'votes'->0->>'status'='DONE','disconnected voters expire';
 assert not ((snap->'votes'->0->'ballots')?users[2]::text),'timeout is not a vote';
 perform set_config('request.jwt.claim.sub',users[2]::text,true);
 denied:=false;begin perform pg_temp.vote_action('vote_nominate',jsonb_build_object('nominee',users[3]));exception when others then denied:=true;end;assert denied,'one nomination daily';
 perform set_config('request.jwt.claim.sub',users[3]::text,true);
 denied:=false;begin perform pg_temp.vote_action('vote_nominate',jsonb_build_object('nominee',users[2]));exception when others then denied:=true;end;assert denied,'one nomination received daily';
 perform pg_temp.vote_action('vote_nominate',jsonb_build_object('nominee',users[4]));
 select id into vid from public.clocktower_live_votes where room_id=rid and status='WAITING';
 perform set_config('request.jwt.claim.sub',users[1]::text,true);perform pg_temp.vote_action('vote_start',jsonb_build_object('vote_id',vid));
 update public.clocktower_live_votes set started_at=clock_timestamp()-interval '6.5 seconds' where id=vid;
 perform set_config('request.jwt.claim.sub',users[4]::text,true);
 denied:=false;begin perform pg_temp.vote_action('vote_cast',jsonb_build_object('vote_id',vid,'yes',true));exception when others then denied:=true;end;assert denied,'spent ghost vote rejected';
 perform pg_temp.vote_action('vote_cast',jsonb_build_object('vote_id',vid,'yes',false));
 perform set_config('request.jwt.claim.sub',users[5]::text,true);snap:=public.clocktower_live_snapshot(eid);assert not(snap?'votes'),'outsider cannot see voting';
 assert not has_table_privilege('authenticated','public.clocktower_live_votes','SELECT');
 perform set_config('request.jwt.claim.sub',users[1]::text,true);perform pg_temp.vote_action('vote_cancel',jsonb_build_object('vote_id',vid));
 update public.clocktower_live_rooms set night=2 where id=rid;
 perform set_config('request.jwt.claim.sub',users[2]::text,true);perform pg_temp.vote_action('vote_nominate',jsonb_build_object('nominee',users[2]));
 assert (select count(*)=3 from public.clocktower_live_votes where room_id=rid),'new day resets nomination limits';
end $$;
rollback;
