// Run with PGLITE_MODULE pointing to an installed @electric-sql/pglite package.
// Uses an isolated, in-memory PostgreSQL database; never contacts production.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const { PGlite } = require(process.env.PGLITE_MODULE || '@electric-sql/pglite');
const ids = { admin:'00000000-0000-0000-0000-000000000001', member:'00000000-0000-0000-0000-000000000002', other:'00000000-0000-0000-0000-000000000003', event:'00000000-0000-0000-0000-000000000004' };
(async () => {
 const db = new PGlite();
 await db.exec(`
 create role anon; create role authenticated; create schema auth;
 create table auth.users(id uuid primary key);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema auth to authenticated,anon;
 create table public.site_roles(user_id uuid primary key,role text);
 create function public.is_main_admin() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from site_roles where user_id=auth.uid() and role='MAIN_ADMIN')$$;
 create table profiles(id uuid primary key,activity_name text);
 create table events(id uuid primary key,title text,created_by uuid,started_at timestamptz,event_kind text);
 create table event_participants(event_id uuid references events(id) on delete cascade,user_id uuid,joined_at timestamptz,primary key(event_id,user_id));
 create table event_waitlist(event_id uuid references events(id) on delete cascade,user_id uuid,joined_at timestamptz,primary key(event_id,user_id));
 create table event_groups(id uuid primary key,event_id uuid);
 create table event_group_members(group_id uuid,user_id uuid);
 create table promotions(event_id uuid);
 create function public.promote_event_waitlist(p_event_id uuid) returns void language sql as $$insert into promotions values(p_event_id)$$;
 create table notifications(id uuid primary key default gen_random_uuid(),recipient_id uuid,type text,title text,message text,link text,dedupe_key text,is_read boolean default false,updated_at timestamptz default now(),unique(recipient_id,dedupe_key));
 create function public.create_member_notification(p_recipient_id uuid,p_type text,p_title text,p_message text,p_link text,p_dedupe_key text) returns uuid language plpgsql security definer set search_path=public as $$declare v_id uuid; begin if p_recipient_id is null then return null; end if; insert into notifications(recipient_id,type,title,message,link,dedupe_key) values(p_recipient_id,p_type,p_title,p_message,p_link,p_dedupe_key) on conflict(recipient_id,dedupe_key) do update set title=excluded.title,message=excluded.message,link=excluded.link,is_read=false,updated_at=now() returning id into v_id; return v_id; end $$;
 create table push_subscriptions(id uuid primary key default gen_random_uuid(),user_id uuid);
 create table push_settings(id boolean primary key default true,recipient_id uuid);
 create table push_deliveries(subscription_id uuid,notification_id uuid,title text,message text,link text,unique(subscription_id,notification_id));
 create function public.dispatch_participant_push() returns void language sql as $$select$$;
 create function public.cancel_event_join_or_waitlist(p_event_id uuid) returns text language plpgsql security definer set search_path=public as $$declare v_user uuid:=auth.uid(); v_creator uuid; begin if v_user is null then raise exception '로그인이 필요합니다.'; end if; select created_by into v_creator from events where id=p_event_id for update; if not found then raise exception '이벤트를 찾을 수 없습니다.'; end if; if v_creator=v_user then raise exception '이벤트 생성자는 참가를 취소할 수 없습니다.'; end if; delete from event_waitlist where event_id=p_event_id and user_id=v_user; if found then return 'WAITLIST_CANCELLED'; end if; delete from event_group_members gm using event_groups g where gm.group_id=g.id and g.event_id=p_event_id and gm.user_id=v_user; delete from event_participants where event_id=p_event_id and user_id=v_user; if found then perform promote_event_waitlist(p_event_id); return 'CANCELLED'; end if; return 'NONE'; end $$;
 insert into auth.users values('${ids.admin}'),('${ids.member}'),('${ids.other}');
 insert into site_roles values('${ids.admin}','MAIN_ADMIN');
 insert into profiles values('${ids.member}','테스트멤버');
 insert into events values('${ids.event}','테스트 일정','${ids.admin}',now(),'BOARDGAME');
 insert into event_participants values('${ids.event}','${ids.member}','2026-09-01T12:00:00Z');
 insert into push_settings values(true,'${ids.admin}'); insert into push_subscriptions(user_id) values('${ids.admin}');
 `);
 await db.exec(fs.readFileSync('supabase/migrations/20260915010000_event_refund_requests.sql','utf8'));
 await db.exec(`create trigger enqueue_participant_push after insert on notifications for each row execute function enqueue_participant_push()`);
 const rows = async sql => (await db.query(sql)).rows;
 const as = async (user,sql) => {
   await db.exec(`set request.jwt.claim.sub='${user}'; set role authenticated;`);
   try { return await rows(sql); } finally { await db.exec('reset role'); }
 };
 const leave = (method,bank='NULL',account='NULL') => `select public.leave_event_with_refund('${ids.event}','${method}',${bank},${account}) as id`;
 await assert.rejects(as(ids.member,leave('BANK',"'은행'","'invalid'")));
 assert.equal((await rows('select count(*)::int n from event_participants'))[0].n,1);
 assert.equal((await rows('select count(*)::int n from event_refund_requests'))[0].n,0);
 await assert.rejects(as(ids.admin,leave('NONE')));
 const [request] = await as(ids.member,leave('BANK',"'테스트은행'","'123-456-789'"));
 assert.ok(request.id);
 assert.equal((await rows('select count(*)::int n from event_participants'))[0].n,0);
 assert.equal((await rows('select count(*)::int n from promotions'))[0].n,1);
 assert.equal((await rows("select count(*)::int n from notifications where type='EVENT_REFUND'"))[0].n,2);
 assert.equal((await rows('select count(*)::int n from push_deliveries'))[0].n,1);
 assert.ok((await rows('select message from notifications')).every(r=>!r.message.includes('123-456')));
 assert.equal((await as(ids.member,'select * from refund_account_presets'))[0].bank,'테스트은행');
 assert.equal((await as(ids.admin,'select * from refund_account_presets')).length,0);
 assert.equal((await as(ids.other,'select * from event_refund_requests')).length,0);
 assert.equal((await as(ids.admin,'select * from event_refund_requests')).length,1);
 assert.equal((await as(ids.member,'select * from event_refund_requests')).length,1);
 await assert.rejects(as(ids.member,"update refund_account_presets set bank='tampered'"));
 await assert.rejects(as(ids.member,leave('KAKAOPAY')));
 assert.equal((await rows('select count(*)::int n from event_refund_requests'))[0].n,1);
 await db.exec(`insert into event_waitlist values('${ids.event}','${ids.member}','2026-09-14T12:00:00Z');`);
 await as(ids.member,leave('KAKAOPAY'));
 const both = await rows('select method,bank,account_number,first_joined_at from event_refund_requests order by requested_at');
 assert.equal(both[1].bank,null); assert.equal(both[1].account_number,null);
 assert.equal(new Date(both[0].first_joined_at).toISOString(),new Date(both[1].first_joined_at).toISOString());
 assert.equal((await rows('select count(*)::int n from event_waitlist'))[0].n,0);
 await db.exec(`insert into event_participants values('${ids.event}','${ids.member}',now());`);
 await as(ids.member,leave('NONE'));
 assert.equal((await rows('select count(*)::int n from event_refund_requests'))[0].n,2);
 await db.exec(`insert into event_participants values('${ids.event}','${ids.member}',now());
 create function fail_refund_notification() returns trigger language plpgsql as $$begin raise exception 'notification failed'; end$$;
 create trigger fail_refund_notification before insert on notifications for each row execute function fail_refund_notification();`);
 await assert.rejects(as(ids.member,leave('BANK',"'새은행'","'987654321'")));
 assert.equal((await rows('select count(*)::int n from event_participants'))[0].n,1);
 assert.equal((await rows('select bank from refund_account_presets'))[0].bank,'테스트은행');
 assert.equal((await rows('select count(*)::int n from event_refund_requests'))[0].n,2);
 await db.exec('drop trigger fail_refund_notification on notifications');
 await as(ids.member,leave('BANK',"'새은행'","'987654321'"));
 assert.equal((await rows('select bank from refund_account_presets'))[0].bank,'새은행');
 await db.exec(`select create_member_notification('${ids.admin}','EVENT_JOINED','참가','참가 알림','/notifications','existing-push-test');`);
 assert.equal((await rows("select count(*)::int n from push_deliveries where title='참가'"))[0].n,1);
 await db.exec(`delete from events where id='${ids.event}'`);
 assert.equal((await rows('select count(*)::int n from event_refund_requests where event_id is null'))[0].n,3);
 console.log('PASS: migration, BANK/KAKAOPAY/NONE, presets, first join on reentry, private RLS, creator/duplicate/invalid guards, atomic rollback, waitlist cancellation, promotion call, admin/requester notifications, existing/new push, event deletion compatibility');
 await db.close();
})().catch(e=>{console.error(e);process.exitCode=1;});
