const fs=require("fs");
const {PGlite}=require("../.local-reference/clocktower/test-runtime/node_modules/@electric-sql/pglite");
(async()=>{
 const db=new PGlite();
 await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;create table public.profiles(id uuid primary key references auth.users,activity_name text,gender text,updated_at timestamptz default now());`);
 await db.exec(fs.readFileSync("supabase/migrations/20260928020000_tichu_rooms.sql","utf8"));
 await db.exec(fs.readFileSync("supabase/migrations/20260929010000_tichu_full_game.sql","utf8"));
 await db.exec(fs.readFileSync("supabase/migrations/20260929020000_tichu_round_end_hotfix.sql","utf8"));
 await db.exec(fs.readFileSync("supabase/migrations/20260929030000_tichu_waiting_score_setting.sql","utf8"));
 await db.exec(fs.readFileSync("supabase/migrations/20260929040000_tichu_force_leave_game.sql","utf8"));
 await db.exec(fs.readFileSync("supabase/migrations/20260929050000_tichu_host_next_round.sql","utf8"));
 await db.exec(fs.readFileSync("supabase/migrations/20260929060000_tichu_host_leave_cleanup.sql","utf8"));
 await db.exec(fs.readFileSync("supabase/migrations/20260929070000_tichu_avatars.sql","utf8"));
 const ids=[1,2,3,4].map(n=>`00000000-0000-0000-0000-00000000000${n}`);
 for(let i=0;i<4;i++)await db.exec(`insert into auth.users values('${ids[i]}');insert into profiles(id,activity_name,gender) values('${ids[i]}','멤버${i+1}','${i%2?'여':'남'}')`);
 const as=async(i,sql)=>{await db.exec(`select set_config('request.jwt.claim.sub','${ids[i]}',false)`);return db.query(sql)};
 await as(0,"select public.tichu_set_avatar(7,11,4)");
 let avatar=(await as(0,"select public.tichu_my_avatar() avatar")).rows[0].avatar;
 if(Number(avatar.avatar)!==7||Number(avatar.accessory)!==11||Number(avatar.frame)!==4)throw new Error("avatar save failed");
 const room=(await as(0,`select public.tichu_create_room(null,1000,15) id`)).rows[0].id;
 for(let i=1;i<4;i++)await as(i,`select public.tichu_join_room('${room}'::uuid)`);
 await as(0,`select public.tichu_set_target_score('${room}',1200)`);
 if(Number((await db.query(`select target_score from tichu_rooms where id='${room}'`)).rows[0].target_score)!==1200)throw new Error("waiting target score failed");
 for(let i=0;i<4;i++)await as(i,`select public.tichu_toggle_ready('${room}')`);
 await as(0,`select public.tichu_start_room('${room}')`);
 let state=(await db.query(`select status,(select min(cardinality(cards)) from tichu_hands) cards from tichu_rooms where id='${room}'`)).rows[0];
 if(state.status!=="GRAND"||Number(state.cards)!==8)throw new Error("8-card grand phase failed");
 for(let i=0;i<4;i++)await as(i,`select public.tichu_grand_choice('${room}',false)`);
 state=(await db.query(`select status,(select min(cardinality(cards)) from tichu_hands) cards from tichu_rooms where id='${room}'`)).rows[0];
 if(state.status!=="EXCHANGE"||Number(state.cards)!==14)throw new Error("14-card exchange phase failed");
 const hands=(await db.query(`select user_id,cards from tichu_hands where room_id='${room}' order by user_id`)).rows;
 for(let i=0;i<4;i++){const targets=ids.filter(x=>x!==ids[i]);for(let j=0;j<3;j++)await as(i,`select public.tichu_give_card('${room}','${targets[j]}',${hands[i].cards[j]})`)}
 state=(await db.query(`select status,(select min(cardinality(cards)) from tichu_hands) cards from tichu_rooms where id='${room}'`)).rows[0];
 if(state.status!=="PLAYING"||Number(state.cards)!==14)throw new Error("one-card exchange failed");
 await db.exec(`delete from tichu_finished where room_id='${room}';insert into tichu_finished(room_id,user_id,finish_order) values('${room}','${ids[0]}',1),('${room}','${ids[1]}',2),('${room}','${ids[2]}',3);update tichu_hands set cards=case when user_id='${ids[3]}' then array[12] else '{}'::int[] end where room_id='${room}';update tichu_rooms set round_no=1 where id='${room}';select public.tichu_end_round('${room}')`);
 state=(await db.query(`select status,jsonb_array_length(round_history) history from tichu_rooms where id='${room}'`)).rows[0];
 if(state.status!=="ROUND_END"||Number(state.history)!==1)throw new Error("round-end scoring failed");
 await as(0,`select public.tichu_start_room('${room}')`);
 state=(await db.query(`select status,round_no from tichu_rooms where id='${room}'`)).rows[0];
 if(state.status!=="GRAND"||Number(state.round_no)!==2)throw new Error("host next round failed");
 await as(1,`select public.tichu_leave_room('${room}')`);
 state=(await db.query(`select status,(select count(*) from tichu_players where room_id='${room}') players from tichu_rooms where id='${room}'`)).rows[0];
 if(state.status!=="FINISHED"||Number(state.players)!==3)throw new Error("force leave failed");
 await as(0,`select public.tichu_leave_room('${room}')`);
 state=(await db.query(`select count(*) rooms from tichu_rooms where id='${room}'`)).rows[0];
 if(Number(state.rooms)!==0)throw new Error("host leave did not delete room");
 console.log("PASS: Tichu setup, exchange, scoring and forced game leave");await db.close();
})().catch(e=>{console.error(e);process.exit(1)});
