"use client";
import { useState } from 'react';
import { BMR_ROLES, BMR_HINTS, bmrRandomRoles, bmrInformationDraft, bmrOrder, bmrPreset, bmrSetupErrors, bmrExecutionCandidate, type BmrMemberState, type BmrRequestOptions } from '@/lib/clocktower/bmr';
import type { LiveMember, LiveRequest, LiveState } from '@/lib/clocktower/live';
import { nextFlowLabel } from '@/lib/clocktower/flow';
import ClocktowerSeating from './ClocktowerSeating';
import ClocktowerPopup from './ClocktowerPopup';
const field='w-full rounded-xl border border-white/15 bg-zinc-900 p-3 text-white';
const button='rounded-xl bg-violet-400 px-4 py-3 font-bold text-zinc-950 disabled:opacity-40';
const subtle='rounded-xl border border-white/20 px-4 py-3 text-sm disabled:opacity-40';
type Run=(action:string,data?:Record<string,unknown>)=>Promise<boolean>;
export default function ClocktowerBmrHost({state,run,busy,error}:{state:LiveState;run:Run;busy:boolean;error:string}) {
 const room=state.room!, members=state.members??[], requests=state.requests??[];
 const order=bmrOrder(room.night),cursor=state.bmr?.cursor??0,step=order[cursor];
 const [edit,setEdit]=useState<LiveMember|null>(null),[randomDraft,setRandomDraft]=useState<LiveMember[]|null>(null),[notesOpen,setNotesOpen]=useState(false),[flowOpen,setFlowOpen]=useState(false),[endOpen,setEndOpen]=useState(false),[layoutEditing,setLayoutEditing]=useState(false);
 const [stepNote,setStepNote]=useState('');
 const [draftRevision,setDraftRevision]=useState(state.bmr_revision??0);
 const setupErrors=bmrSetupErrors(members);
 const active=requests.find(q=>q.status==='OPEN'||q.status==='SUBMITTED');
 const pending=requests.filter(q=>q.status==='OPEN'||q.status==='SUBMITTED'||q.status==='RESOLVED'&&!q.acknowledged);
 const remainingMissions=(state.mission_progress??[]).some(m=>m.completed<m.total);
 const locked=busy||layoutEditing;
 const nextDisabled=locked||room.phase==='SETUP'&&(setupErrors.length>0||!!room.roles_released&&members.some(m=>!m.role_confirmed))||room.phase==='NIGHT'&&(!state.bmr?.completed||pending.length>0||remainingMissions)||(state.votes??[]).some(v=>['WAITING','RUNNING'].includes(v.status));
 return <div className="space-y-6">
  <section className="rounded-2xl border border-amber-300/30 bg-amber-300/5 p-5"><h2 className="text-xl font-bold text-amber-200">피로 물든 달 · 이야기꾼 진행</h2><p className="mt-2 text-sm leading-7 text-zinc-300">밤 시트에 따라 요청하고 결과를 전달합니다. 사망·부활·취함·중독·보호·능력 소모와 승리는 이야기꾼이 판정하여 마도서에 저장해 주세요. 상태 표시는 자동 적용·만료되지 않습니다.</p><div className="mt-4 flex flex-wrap gap-2">{room.phase!=='ENDED'&&<><button disabled={nextDisabled} className={button} onClick={()=>setFlowOpen(true)}>다음 페이즈 · {nextFlowLabel(state)}</button><button disabled={locked||room.phase==='SETUP'} className={subtle} onClick={()=>{setDraftRevision(state.bmr_revision??0);setEndOpen(true);}}>승리 판정·게임 종료</button></>}{room.phase==='ENDED'&&<p>{room.result_round_id?'플레이 결과 저장 완료':'게임 종료'}</p>}<button className={subtle} onClick={()=>{setDraftRevision(state.bmr_revision??0);setNotesOpen(true);}}>진행 메모</button></div></section>
  {room.phase==='SETUP'&&<section className="rounded-2xl border border-white/15 p-5"><h3 className="font-bold">역할 준비</h3>{!room.roles_released&&<button disabled={busy||members.length<5||members.length>15} className={`${subtle} mt-3`} onClick={()=>{setDraftRevision(state.bmr_revision??0);setRandomDraft(bmrRandomRoles(members));}}>무작위 배정 초안</button>}<p className="my-3 text-sm text-zinc-400">마도서의 각 멤버를 눌러 역할을 배정하세요. 대부가 있으면 외지인 수를 기본 구성에서 −1 또는 +1로 조정합니다. 미치광이에게 표시할 악마는 실제 악마와 같아도 됩니다.</p>{setupErrors.map(e=><p key={e} className="text-sm text-amber-200">{e}</p>)}{room.roles_released&&<><p>역할 확인 {members.filter(m=>m.role_confirmed).length}/{members.length}</p>{members.filter(m=>!m.role_confirmed).map(m=><span className="mr-3 text-zinc-400" key={m.user_id}>{m.name} 대기</span>)}<button disabled={busy} className={subtle} onClick={()=>void run('roles_reset')}>준비로 돌아가기</button></>}</section>}
  {room.phase==='NIGHT'&&<section className="space-y-4 rounded-3xl border border-violet-300/30 p-5"><h3 className="text-xl font-bold">{room.night}일차 밤 · {state.bmr?.completed?'밤 순서 확인 완료':`${cursor+1}/${order.length} ${step}`}</h3><div className="flex flex-wrap gap-2">{order.map((role,i)=><span key={role} className={`rounded-full px-2 py-1 text-xs ${i===cursor?'bg-violet-400 text-black':i<cursor?'text-emerald-300':'text-zinc-500'}`}>{role}</span>)}</div><p className="whitespace-pre-wrap text-sm leading-7 text-amber-100">{BMR_HINTS[step]}</p>
   {!state.bmr?.completed&&<><BmrRequestForm key={`${room.night}:${cursor}`} step={step} state={state} run={run} busy={locked||!!active}/><label className="block text-sm">처리 내용 / 건너뛰는 이유<input maxLength={1000} className={`${field} mt-2`} value={stepNote} onChange={e=>setStepNote(e.target.value)} placeholder="예: 게임에 없음 / 조건 불충족 / 선택·판정 저장 완료"/></label><div className="flex flex-wrap gap-2"><button disabled={locked||!!active||!stepNote.trim()} className={button} onClick={async()=>{if(await run('bmr_step',{note:stepNote}))setStepNote('');}}>{step==='새벽'?'밤 판정 확인 완료':'처리 완료 · 다음 차례'}</button><button disabled={locked||!!active} className={subtle} onClick={()=>setStepNote('게임에 없거나 이번 밤 발동 조건이 없어 건너뜀')}>조건 없음</button></div></>}
   <p className="text-xs text-zinc-400">결과를 전달하면 상대의 확인을 기다리지 않고 다음 차례를 진행할 수 있습니다. 낮 전환은 모두 확인한 뒤 가능합니다.</p>
  </section>}
  {room.phase==='DAY'&&<section className="rounded-2xl border border-white/15 p-5"><h3 className="font-bold">낮 판정 체크</h3><p className="mt-2 text-sm leading-7 text-amber-100">험담꾼의 공개 발언과 달의 자손의 공개 선택은 현장에서 듣고 진행 메모에 기록하세요. 처형 전 악마의 변호사·평화주의자·어릿광대·선원·찻집 여인, 처형 후 음유시인·대부·주모자를 확인하세요. 마도서의 상태 변경은 낮에는 즉시 공개됩니다.</p></section>}
  <ClocktowerSeating roomId={room.id} storyteller members={members} phase={room.phase} night={room.night} myId={state.my_id} layout={room.seating_layout} revision={room.seating_revision} editable={room.phase==='SETUP'&&!room.roles_released} busy={busy} onEditingChange={setLayoutEditing} save={(layout,revision)=>run('save_layout',{layout,revision})} sync={()=>void run('sync_participants')} swap={(a,b)=>run('swap_seats',{first_user_id:a.user_id,second_user_id:b.user_id,first_seat:a.seat,second_seat:b.seat})} vote={(state.votes??[]).find(v=>v.status==='RUNNING')} onRecordVote={(voteId,userId,yes)=>run('vote_record',{vote_id:voteId,user_id:userId,yes})}/>
  <section className="rounded-3xl border border-white/15 p-5"><h3 className="text-xl font-bold">마도서 · {members.length}명</h3><div className="mt-4 grid gap-3 sm:grid-cols-2">{members.map(m=><button key={m.user_id} disabled={locked||room.phase==='ENDED'||room.phase==='SETUP'&&room.roles_released} onClick={()=>{setDraftRevision(state.bmr_revision??0);setEdit(m);}} className="rounded-2xl border border-white/15 p-4 text-left disabled:opacity-70"><p className="font-bold">{m.seat}. {m.name} · {m.actual_role||'역할 미배정'}</p><p className="mt-2 text-sm text-violet-200">{m.bmr?.life==='ZOMBIE'?'사망 위장 (실제 생존)':m.alive?'생존':'사망'} · {m.bmr?.faction==='EVIL'?'악':'선'}{m.shown_role!==m.actual_role?` · 본인 표시: ${m.shown_role}`:''}</p><p className="mt-2 text-xs text-amber-200">{[m.bmr?.drunk&&'취함',m.bmr?.poisoned&&'중독',m.bmr?.protected&&'보호',m.bmr?.spent&&'능력 소모'].filter(Boolean).join(' · ')||'상태 표시 없음'}</p><p className="mt-2 whitespace-pre-wrap text-sm text-zinc-400">{m.notes}</p></button>)}</div></section>
  <section className="space-y-3"><h3 className="text-xl font-bold">비공개 요청·결과 · 미확인 {pending.length}</h3>{requests.map(q=><BmrRequestReview key={q.id} q={q} members={members} run={run} busy={locked} ended={room.phase==='ENDED'}/>)}</section>
  {!!state.mission_progress?.length&&<details className="rounded-2xl border border-white/15 p-4"><summary>공통 미션 현황</summary>{state.mission_progress.map(m=><div key={m.user_id} className="mt-3 flex items-center justify-between gap-3"><span>{members.find(x=>x.user_id===m.user_id)?.name} {m.completed}/{m.total}</span>{m.completed<m.total&&<button disabled={busy} className={subtle} onClick={()=>{if(confirm('현장에서 미션을 확인했나요?'))void run('mission_offline',{user_id:m.user_id});}}>현장 완료</button>}</div>)}</details>}
  <details className="rounded-2xl border border-white/15 p-4"><summary>밤·낮 판정 기록</summary>{state.bmr?.history?.map((h,i)=><p key={i} className="mt-3 whitespace-pre-wrap text-sm">{h.night}일차 · {h.step}: {h.note}</p>)}</details>
  {randomDraft&&<ClocktowerPopup title="무작위 역할 초안" busy={busy} onClose={()=>setRandomDraft(null)}><div className="space-y-3">{randomDraft.map(m=><p key={m.user_id}>{m.name} · {m.actual_role}{m.actual_role!==m.shown_role?` (본인 표시: ${m.shown_role})`:null}</p>)}<p className="text-sm text-zinc-400">저장 후 마도서에서 개별 역할을 수정할 수 있습니다.</p>{error&&<p role="alert">{error}</p>}<button disabled={busy} className={subtle} onClick={()=>{setDraftRevision(state.bmr_revision??0);setRandomDraft(bmrRandomRoles(members));}}>다시 섞기</button><button disabled={busy} className={button} onClick={async()=>{if(await run('bmr_save_roles',{bmr_revision:draftRevision,rows:randomDraft.map(m=>({user_id:m.user_id,actual_role:m.actual_role,shown_role:m.shown_role}))}))setRandomDraft(null);}}>이 배정 저장</button></div></ClocktowerPopup>}
  {edit&&<ClocktowerPopup title={`${edit.name} · 역할·상태`} onClose={()=>setEdit(null)} busy={busy}><BmrMemberEditor key={edit.user_id} member={edit} revision={draftRevision} setup={room.phase==='SETUP'} run={run} busy={busy} close={()=>setEdit(null)} error={error}/></ClocktowerPopup>}
  {notesOpen&&<ClocktowerPopup title="이야기꾼 진행 메모" onClose={()=>setNotesOpen(false)} busy={busy}><Notes initial={state.bmr?.notes??''} busy={busy} readOnly={room.phase==='ENDED'} save={async notes=>{if(await run('bmr_notes',{notes,bmr_revision:draftRevision}))setNotesOpen(false);}}/><p className="mt-3 text-xs text-zinc-400">손주, 이전 선택, 포 충전, 취함 기간, 공개 발언, 낮 사망, 주모자의 추가 낮 등을 기록하세요. 이야기꾼만 볼 수 있습니다.</p>{error&&<p role="alert">{error}</p>}</ClocktowerPopup>}
  {flowOpen&&<BmrFlow state={state} run={run} busy={busy} close={()=>setFlowOpen(false)} error={error}/>}
  {endOpen&&<BmrEnd run={(action,data)=>run(action,{...data,bmr_revision:draftRevision})} busy={busy} close={()=>setEndOpen(false)} error={error}/>}
 </div>;
}
function BmrMemberEditor({member,revision,setup,run,busy,close,error}:{member:LiveMember;revision:number;setup:boolean;run:Run;busy:boolean;close:()=>void;error:string}) {
 const [role,setRole]=useState(member.actual_role??''),[shown,setShown]=useState(member.shown_role??''),[notes,setNotes]=useState(member.notes??'');
 const [flags,setFlags]=useState<BmrMemberState>(member.bmr??{life:member.alive?'ALIVE':'DEAD',faction:'GOOD',drunk:false,poisoned:false,protected:false,spent:false});
 return <form className="space-y-4" onSubmit={async e=>{e.preventDefault();if(await run('bmr_member',{bmr_revision:revision,user_id:member.user_id,actual_role:role,shown_role:shown,notes,bmr:flags}))close();}}><fieldset disabled={busy} className="space-y-4"><label className="block">실제 역할<select required className={field} value={role} onChange={e=>{const r=BMR_ROLES.find(r=>r.name===e.target.value)!;setRole(r.name);setShown(r.name==='미치광이'?'':r.name);setFlags({...flags,life:'ALIVE',faction:['악마','하수인'].includes(r.type)?'EVIL':'GOOD'});}}><option value="">역할 선택</option>{BMR_ROLES.map(r=><option key={r.name} value={r.name}>{r.type} · {r.name}</option>)}</select></label>{role==='미치광이'&&<label className="block">본인에게 표시할 악마<select required className={field} value={shown} onChange={e=>setShown(e.target.value)}><option value="">선택</option>{BMR_ROLES.filter(r=>r.type==='악마').map(r=><option key={r.name}>{r.name}</option>)}</select></label>}
 {!setup&&<><label className="block">실제 상태<select className={field} value={flags.life} onChange={e=>setFlags({...flags,life:e.target.value as BmrMemberState['life']})}><option value="ALIVE">생존 / 부활</option><option value="DEAD">실제 사망</option>{role==='좀비얼'&&<option value="ZOMBIE">사망 위장 · 실제 생존</option>}</select></label><label className="block">실제 소속<select className={field} value={flags.faction} onChange={e=>setFlags({...flags,faction:e.target.value as 'GOOD'|'EVIL'})}><option value="GOOD">선</option><option value="EVIL">악</option></select></label></>}
 <div className="flex flex-wrap gap-4">{(['drunk','poisoned','protected','spent'] as const).map((key,i)=><label key={key} className="flex items-center gap-2"><input type="checkbox" checked={flags[key]} onChange={e=>setFlags({...flags,[key]:e.target.checked})}/>{['취함','중독','보호','능력 소모'][i]}</label>)}</div><p className="text-sm leading-7 text-amber-100">{BMR_HINTS[role]}</p><label className="block">원인·기간·능력 메모<textarea maxLength={2000} rows={4} value={notes} onChange={e=>setNotes(e.target.value)} className={field}/></label><p className="text-xs text-zinc-400">밤의 사망·부활은 새벽에 공개됩니다. 보호 표시는 판정 메모이며 자동으로 사망을 막지 않습니다. 부활 시 능력 소모·상태를 확인해 해제하세요.</p>{error&&<p role="alert" className="text-red-300">{error}</p>}<button className={button}>저장</button></fieldset></form>;
}
function BmrRequestForm({step,state,run,busy}:{step:string;state:LiveState;run:Run;busy:boolean}) {
 const members=state.members??[],initial=members.find(m=>m.actual_role===step);
 const preset=bmrPreset(step,state.room!.night);
 const informationDraft=bmrInformationDraft(step,members);
 const [uid,setUid]=useState(initial?.user_id??''),[role,setRole]=useState(step),[count,setCount]=useState(preset.count),[self,setSelf]=useState(preset.self),[options,setOptions]=useState<BmrRequestOptions>(preset.options),[prompt,setPrompt]=useState(preset.prompt);
 function chooseRole(value:string){setRole(value);const p=bmrPreset(value,state.room!.night);setCount(p.count);setOptions(p.options);setSelf(p.self);setPrompt(p.prompt);}
 return <details className="rounded-2xl border border-white/15 p-4" open><summary className="font-bold">능력·정보 요청</summary><form className="mt-4 space-y-3" onSubmit={async e=>{e.preventDefault();await run('bmr_request',{user_id:uid,target_count:count,allow_self:self,options,prompt});}}><fieldset disabled={busy} className="space-y-3"><div className="grid gap-3 sm:grid-cols-2"><label>받는 사람<select required className={field} value={uid} onChange={e=>setUid(e.target.value)}><option value="">선택</option>{members.map(m=><option key={m.user_id} value={m.user_id}>{m.name} · {m.actual_role} ({m.alive?'생존':'사망'})</option>)}</select></label><label>요청 형식<select className={field} value={role} onChange={e=>chooseRole(e.target.value)}>{[...new Set([step,...BMR_ROLES.map(r=>r.name),'하수인 정보','악마 정보'])].map(r=><option key={r}>{r}</option>)}</select></label></div><p className="text-xs text-zinc-400">미치광이는 본인이 믿는 악마의 요청 형식을 선택하세요. 부활 후 추가 정보도 여기서 요청할 수 있습니다.</p><label className="block">선택 인원<select className={field} value={count} onChange={e=>setCount(Number(e.target.value))}>{[0,1,2,3].map(n=><option key={n} value={n}>{n===0?'정보 / 캐릭터 선택만':`${n}명 선택`}</option>)}</select></label><div className="flex flex-wrap gap-4"><label><input type="checkbox" checked={self} onChange={e=>setSelf(e.target.checked)}/> 본인 선택 가능</label><label><input type="checkbox" checked={!!options.character} onChange={e=>setOptions({...options,character:e.target.checked})}/> 캐릭터 선택</label><label><input type="checkbox" checked={!!options.pass} onChange={e=>setOptions({...options,pass:e.target.checked})}/> 능력 쉬기 가능</label></div>{count===3&&options.pass&&<p className="text-sm text-amber-200">충전된 포는 쉬기 가능을 해제하세요.</p>}<label className="block">참가자에게 보낼 안내<textarea required maxLength={2000} rows={3} className={field} value={prompt} onChange={e=>setPrompt(e.target.value)}/></label>{informationDraft&&(step!=='대부'||state.room!.night===1)&&<button type="button" className={subtle} onClick={()=>setPrompt(informationDraft)}>초기 정보 초안 불러오기 · 수정 후 전달</button>}<button className={button}>요청 보내기</button></fieldset></form></details>;
}
function BmrRequestReview({q,members,run,busy,ended}:{q:LiveRequest;members:LiveMember[];run:Run;busy:boolean;ended:boolean}) {
 const [result,setResult]=useState(q.target_count===0&&!q.bmr_options?.character?q.prompt:'선택을 확인했습니다.');
 const who=members.find(m=>m.user_id===q.user_id);
 return <article className="space-y-3 rounded-2xl border border-white/15 p-4"><p className="font-bold">{q.night}일차 · {who?.actual_role} ({who?.name}) · {q.status==='OPEN'?'선택 대기':q.status==='SUBMITTED'?'판정 대기':q.status==='CANCELLED'?'취소':q.acknowledged?'확인 완료':'결과 확인 대기'}</p><p className="whitespace-pre-wrap text-sm text-zinc-400">{q.prompt}</p>{!!q.targets.length&&<p className="text-amber-200">선택: {q.targets.map(id=>members.find(m=>m.user_id===id)?.name).join(', ')}</p>}{q.bmr_answer?.pass&&<p className="text-amber-200">이번 능력 쉬기</p>}{q.bmr_answer?.character&&<p className="text-amber-200">선택 캐릭터: {q.bmr_answer.character}</p>}{q.status==='SUBMITTED'&&!ended&&<><p className="text-xs text-amber-100">능력의 성공·실패와 상태를 확인하고 마도서에 저장한 뒤 결과를 전달하세요. 정보를 받지 않는 역할에는 성공 여부를 알려주지 마세요.</p><textarea maxLength={2000} rows={3} value={result} onChange={e=>setResult(e.target.value)} className={field}/><button disabled={busy||!result.trim()} className={button} onClick={()=>void run('bmr_resolve',{request_id:q.id,result})}>판정 확인 · 결과 전달</button></>}{q.result&&<p className="whitespace-pre-wrap text-emerald-200">{q.result}</p>}{!ended&&<div className="flex flex-wrap gap-2">{q.status==='RESOLVED'&&!q.acknowledged&&<button disabled={busy} className={subtle} onClick={()=>{if(confirm('현장에서 결과 확인을 마쳤나요?'))void run('ack_offline',{request_id:q.id});}}>현장 확인 완료</button>}{['OPEN','SUBMITTED'].includes(q.status)&&<button disabled={busy} className={subtle} onClick={()=>{if(confirm('요청을 취소할까요?'))void run('cancel',{request_id:q.id});}}>취소</button>}</div>}</article>;
}
function Notes({initial,busy,save,readOnly=false}:{initial:string;busy:boolean;readOnly?:boolean;save:(value:string)=>Promise<void>}){const [value,setValue]=useState(initial);return <form onSubmit={e=>{e.preventDefault();if(!readOnly)void save(value);}}><textarea readOnly={readOnly} className={field} rows={12} maxLength={10000} value={value} onChange={e=>setValue(e.target.value)}/>{!readOnly&&<button disabled={busy} className={`${button} mt-4`}>메모 저장</button>}</form>;}
function BmrFlow({state,run,busy,close,error}:{state:LiveState;run:Run;busy:boolean;close:()=>void;error:string}) {
 const room=state.room!,execution=room.phase==='DAY'&&room.day_stage==='NOMINATIONS';
 const candidate=bmrExecutionCandidate(state.votes??[]),member=state.members?.find(m=>m.user_id===candidate);
 const [expectedRevision]=useState({bmr_revision:state.bmr_revision??0,revision:room.flow_revision??0});
 const [reviewed,setReviewed]=useState(false),[life,setLife]=useState(''),[note,setNote]=useState('');
 return <ClocktowerPopup title={`다음 단계 · ${nextFlowLabel(state)}`} onClose={close} busy={busy}><div className="space-y-4">{execution?<><p className="text-xl font-bold">처형 후보: {member?.name??'없음'}</p>{member&&<label className="block">보호와 사망 위장을 판정한 후 상태<select className={field} value={life} onChange={e=>setLife(e.target.value)}><option value="">판정 선택</option><option value="DEAD">실제 사망</option>{member.bmr?.life!=='DEAD'&&<option value="ALIVE">처형되지만 생존</option>}{member.actual_role==='좀비얼'&&member.bmr?.life!=='DEAD'&&<option value="ZOMBIE">좀비얼 사망 위장</option>}</select></label>}<p className="text-sm leading-7 text-amber-200">처형과 사망은 다릅니다. 음유시인·대부·어릿광대 등의 후속 상태는 마도서에 반영하세요. 주모자·악마 사망으로 게임이 끝나야 한다면 이 창을 닫고 승리 판정에서 종료하세요.</p><textarea className={field} maxLength={1000} value={note} onChange={e=>setNote(e.target.value)} placeholder="처형·보호·후속 능력 판정 메모"/><label className="flex items-start gap-3"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>후속 효과와 승리 조건을 확인했으며 다음 밤을 진행합니다.</label></>:<p>{room.phase==='NIGHT'?'마도서의 생존·사망 상태가 모든 참가자에게 공개됩니다.':room.phase==='SETUP'&&!room.roles_released?'저장된 역할을 각 참가자에게 비공개로 배포합니다.':'다음 단계로 넘어갑니다.'}</p>}{error&&<p className="text-red-300" role="alert">{error}</p>}<button disabled={busy||execution&&(!reviewed||!!member&&!life||!note.trim())} className={button} onClick={async()=>{if(await run('flow_next',{...expectedRevision,execution:candidate,execution_life:life,reviewed,note}))close();}}>확정</button></div></ClocktowerPopup>;
}
function BmrEnd({run,busy,close,error}:{run:Run;busy:boolean;close:()=>void;error:string}) {
 const [winner,setWinner]=useState(''),[reason,setReason]=useState('');return <ClocktowerPopup title="승리 판정·게임 종료" busy={busy} onClose={close}><form className="space-y-4" onSubmit={async e=>{e.preventDefault();if(confirm('선택한 진영의 승리로 종료하고 플레이 이력을 저장할까요?')&&await run('bmr_end',{winner,reason}))close();}}><p className="text-sm leading-7 text-amber-100">좀비얼의 실제 생존, 주모자의 추가 낮, 건달의 최종 소속을 확인하세요. 마도서에 저장된 실제 역할·진영으로 결과를 저장합니다.</p><select required className={field} value={winner} onChange={e=>setWinner(e.target.value)}><option value="">승리 진영 선택</option><option value="GOOD">선 승리</option><option value="EVIL">악 승리</option></select><textarea required className={field} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)} placeholder="승리 판정 사유"/>{error&&<p role="alert">{error}</p>}<button disabled={busy} className={button}>종료·결과 저장</button></form></ClocktowerPopup>;
}
