"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { getEventGames } from "@/lib/services/events";
import type { EventParticipant } from "@/types/event";

type Props={eventId:string;participants:EventParticipant[]};
type Games=Awaited<ReturnType<typeof getEventGames>>;
type PlayerResult=Games[number]["rounds"][number]["players"][number]&{gameName:string;resultType:string;roundNumber:number};

export default function EventStatistics({eventId,participants}:Props){
 const supabase=useMemo(()=>createClient(),[]);const[games,setGames]=useState<Games>([]);const[loading,setLoading]=useState(true);const[query,setQuery]=useState("");const[selectedId,setSelectedId]=useState<string|null>(null);
 const load=useCallback(async()=>{try{setGames(await getEventGames(supabase,eventId));}catch(e){console.error("통계 조회 오류",e);}finally{setLoading(false)}},[eventId,supabase]);useEffect(()=>{void load()},[load]);
 if(loading)return <section className="h-48 animate-pulse rounded-3xl bg-white/[0.03]"/>;
 const rounds=games.flatMap(game=>game.rounds.map(round=>({game,round})));
 const results:PlayerResult[]=rounds.flatMap(({game,round})=>round.players.map(player=>({...player,gameName:game.game?.name||"게임",resultType:game.result_type,roundNumber:round.round_number})));
 const memberName=(id:string)=>participants.find(p=>p.user_id===id)?.profile?.activity_name?.trim()||"회원";
 const memberIds=[...new Set(results.map(r=>r.user_id))].sort((a,b)=>memberName(a).localeCompare(memberName(b),"ko"));
 const filtered=memberIds.filter(id=>memberName(id).includes(query.trim()));
 const gameCounts=new Map<string,number>();rounds.forEach(({game})=>{const name=game.game?.name||"게임";gameCounts.set(name,(gameCounts.get(name)||0)+1)});const gameRows=[...gameCounts].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0],"ko"));
 const selectedResults=selectedId?results.filter(r=>r.user_id===selectedId):[];
 return <><section className="rounded-3xl border border-white/10 bg-white/[0.03] p-5 text-white sm:p-7"><div><p className="text-sm font-semibold text-amber-300">EVENT STATISTICS</p><h2 className="mt-1 text-2xl font-bold">이벤트 통계</h2></div><div className="mt-5 grid grid-cols-3 gap-3"><Summary label="총 플레이" value={`${rounds.length}판`}/><Summary label="게임" value={`${gameCounts.size}종`}/><Summary label="플레이 참가자" value={`${memberIds.length}명`}/></div><div className="mt-5 rounded-2xl border border-white/10 p-4"><h3 className="font-bold">게임별 통계</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{gameRows.map(([name,count])=><div key={name} className="flex justify-between rounded-xl bg-white/[0.04] px-3 py-2 text-sm"><span>{name}</span><strong className="text-amber-300">{count}판</strong></div>)}{!gameRows.length&&<p className="text-sm text-zinc-600">아직 플레이 기록이 없습니다.</p>}</div></div><div className="mt-5"><div className="flex items-end justify-between"><div><h3 className="font-bold">참가자 통계</h3><p className="mt-1 text-xs text-zinc-500">가나다순 · 이름을 누르면 상세 기록이 열립니다.</p></div></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="이름 검색" className="mt-3 h-12 w-full rounded-xl border border-white/10 bg-zinc-900 px-4 outline-none focus:border-amber-400"/><div className="mt-3 overflow-hidden rounded-2xl border border-white/10">{filtered.map(id=>{const count=results.filter(r=>r.user_id===id).length;return <button key={id} onClick={()=>setSelectedId(id)} className="flex min-h-14 w-full items-center justify-between border-b border-white/10 px-4 text-left last:border-0 hover:bg-white/5"><span className="font-semibold">{memberName(id)}</span><span className="text-sm text-zinc-400">{count}판 <b className="ml-2 text-amber-300">›</b></span></button>})}{!filtered.length&&<p className="py-8 text-center text-sm text-zinc-600">표시할 참가자가 없습니다.</p>}</div></div></section>{selectedId&&<MemberDetail name={memberName(selectedId)} results={selectedResults} onClose={()=>setSelectedId(null)}/>}</>;
}

function Summary({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/10 bg-zinc-900/60 p-4"><p className="text-xs text-zinc-500">{label}</p><p className="mt-2 text-xl font-bold text-amber-300">{value}</p></div>}

function MemberDetail({name,results,onClose}:{name:string;results:PlayerResult[];onClose:()=>void}){const distinct=new Set(results.map(r=>r.gameName)).size;const scores=results.filter(r=>r.score!==null);const firsts=results.filter(r=>r.rank===1).length;const roles=results.filter(r=>r.is_winner!==null);const wins=roles.filter(r=>r.is_winner).length;return <div className="fixed inset-0 z-[110] flex items-end bg-black/70 sm:items-center sm:justify-center" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="max-h-[92dvh] w-full overflow-y-auto rounded-t-3xl border border-white/10 bg-zinc-950 p-5 text-white sm:max-w-lg sm:rounded-3xl sm:p-7"><div className="flex justify-between"><div><p className="text-sm text-amber-300">MEMBER STATISTICS</p><h2 className="text-2xl font-bold">{name}</h2></div><button onClick={onClose} className="h-11 w-11 rounded-full bg-white/10 text-xl">×</button></div><div className="mt-5 grid grid-cols-2 gap-3"><Summary label="총 플레이" value={`${results.length}판`}/><Summary label="플레이 게임" value={`${distinct}종`}/><Summary label="등수형 1등" value={`${firsts}회`}/><Summary label="역할형 전적" value={roles.length?`${wins}승 ${roles.length-wins}패`:"기록 없음"}/><Summary label="역할형 승률" value={roles.length?`${Math.round(wins/roles.length*100)}%`:"-"}/><Summary label="최고 점수" value={scores.length?`${Math.max(...scores.map(r=>r.score||0))}점`:"-"}/></div><h3 className="mt-6 font-bold">플레이 기록</h3><div className="mt-3 space-y-2">{results.map((r,i)=><div key={`${r.id}-${i}`} className="rounded-xl bg-white/[0.05] p-3"><div className="flex justify-between"><strong>{r.gameName}</strong><span className="text-xs text-zinc-500">{r.roundNumber}판</span></div><p className="mt-1 text-sm text-amber-300">{r.resultType==="ROLE"?(r.role_name?`${r.role_name} · ${r.is_winner?"승리":"패배"}`:"미입력"):r.resultType==="SIMPLE_SCORE"?(r.rank?`${r.rank}등`:"미입력"):(r.score!==null?`${r.score}점`:"미입력")}</p></div>)}</div></section></div>}
