"use client";

import { useCallback,useEffect,useMemo,useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { clearGroups,getEventGroups,saveGroups } from "@/lib/services/groups";
import { getEventGames } from "@/lib/services/events";
import { createRound } from "@/lib/services/rounds";
import type { GroupDraft,GroupGame,GroupParticipant } from "@/types/group";
import type { EventGame } from "@/types/event";
import GameCard from "@/components/events/GameCard";

type Props={eventId:string;participants:GroupParticipant[];currentUserId?:string|null;canManage?:boolean};
const label=(p:GroupParticipant)=>p.profile?.activity_name?.trim()||"회원";
const newId=()=>`draft-${Date.now()}-${Math.random().toString(36).slice(2)}`;

export default function GroupSection({eventId,participants,currentUserId,canManage}:Props){
 const supabase=useMemo(()=>createClient(),[]);const [drafts,setDrafts]=useState<GroupDraft[]>([]);const [games,setGames]=useState<GroupGame[]>([]);const [eventGames,setEventGames]=useState<EventGame[]>([]);const [selectedUser,setSelectedUser]=useState<string|null>(null);const [busy,setBusy]=useState(false);const [managerId,setManagerId]=useState(currentUserId??null);const [manageable,setManageable]=useState(Boolean(canManage));
 const load=useCallback(async()=>{const [groups,eventGameRows]=await Promise.all([getEventGroups(supabase,eventId),getEventGames(supabase,eventId)]);setGames(eventGameRows.map(game=>({id:game.id,game_id:game.game_id,game:game.game?{id:game.game.id,name:game.game.name}:null})));setEventGames(eventGameRows);setDrafts(groups.map(group=>({id:group.id,name:group.name,sessionId:group.session_id,userIds:group.members.map(member=>member.user_id)})));},[eventId,supabase]);
 useEffect(()=>{void load().catch(console.error);void Promise.all([supabase.auth.getUser(),supabase.from("events").select("created_by").eq("id",eventId).single()]).then(([auth,event])=>{const uid=currentUserId??auth.data.user?.id??null;setManagerId(uid);setManageable(Boolean(canManage||(uid&&event.data?.created_by===uid)));});},[canManage,currentUserId,eventId,load,supabase]);
 const assigned=new Set(drafts.flatMap(group=>group.userIds));const unassigned=participants.filter(p=>!assigned.has(p.user_id));
 function addGroup(){setDrafts(c=>[...c,{id:newId(),name:`${c.length+1}조`,sessionId:null,userIds:[]}]);}
 function move(userId:string,groupId:string|null){setDrafts(c=>c.map(group=>({...group,userIds:group.userIds.filter(id=>id!==userId)})).map(group=>group.id===groupId?{...group,userIds:[...group.userIds,userId]}:group));setSelectedUser(null);}
 function autoBalance(){const count=Math.max(2,drafts.length||Math.ceil(participants.length/4));const next:Array<GroupDraft>=Array.from({length:count},(_,i)=>drafts[i]?{...drafts[i],userIds:[]}:{id:newId(),name:`${i+1}조`,sessionId:null,userIds:[]});participants.forEach((p,i)=>next[i%count].userIds.push(p.user_id));setDrafts(next);}
 async function save(){if(!managerId)return;try{setBusy(true);await saveGroups(supabase,eventId,managerId,drafts);await load();alert("조 편성을 저장했습니다.");}catch(e){alert(typeof e==="object"&&e&&"message" in e?String(e.message):"조 편성 저장에 실패했습니다.");}finally{setBusy(false);}}
 async function reset(){if(!confirm("저장된 조 편성을 모두 초기화할까요?"))return;try{setBusy(true);await clearGroups(supabase,eventId);setDrafts([]);}catch(e){alert(typeof e==="object"&&e&&"message" in e?String(e.message):"초기화에 실패했습니다.");}finally{setBusy(false);}}
 async function addGroupRound(group:GroupDraft){if(group.id.startsWith("draft-")){alert("먼저 조 편성을 저장해 주세요.");return;}if(!group.sessionId){alert("먼저 이 조의 게임을 선택하고 조 편성을 저장해 주세요.");return;}if(!group.userIds.length){alert("조에 참가자가 없습니다.");return;}try{setBusy(true);await createRound(supabase,group.sessionId,group.userIds,group.id);await load();}catch(e){alert(typeof e==="object"&&e&&"message" in e?String(e.message):"판 추가에 실패했습니다.");}finally{setBusy(false);}}
 return <section className="mt-10 rounded-3xl border border-white/10 bg-white/[0.03] p-5 text-white sm:p-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-semibold text-amber-300">GROUP ASSIGNMENT</p><h2 className="mt-1 text-2xl font-bold">조 편성</h2></div>{manageable&&<div className="flex gap-2"><button onClick={autoBalance} className="min-h-11 rounded-xl bg-white/10 px-4">자동 균등 배정</button><button onClick={addGroup} className="min-h-11 rounded-xl bg-amber-400 px-4 font-bold text-zinc-950">+ 조 추가</button></div>}</div>
 <div className="mt-5 rounded-2xl border border-dashed border-white/10 p-4"><p className="text-sm font-bold text-zinc-300">미배정 {unassigned.length}명</p><div className="mt-3 flex flex-wrap gap-2">{unassigned.map(p=><button key={p.user_id} onClick={()=>manageable&&setSelectedUser(p.user_id)} className={`min-h-11 rounded-xl px-4 ${selectedUser===p.user_id?"bg-amber-400 text-zinc-950":"bg-white/10"}`}>{label(p)}</button>)}</div></div>
 {selectedUser&&<div className="mt-3 rounded-xl bg-amber-400/10 p-3 text-sm text-amber-200">선택한 참가자를 이동할 조를 누르세요. <button onClick={()=>setSelectedUser(null)} className="ml-2 underline">취소</button></div>}
 <div className="mt-5 space-y-5">{drafts.map(group=>{const selectedGame=eventGames.find(game=>game.id===group.sessionId);return <article key={group.id} onClick={()=>selectedUser&&move(selectedUser,group.id)} className={`rounded-2xl border p-4 ${selectedUser?"cursor-pointer border-amber-400/50":"border-white/10"}`}><div className="flex gap-2"><input disabled={!manageable} value={group.name} onChange={e=>setDrafts(c=>c.map(g=>g.id===group.id?{...g,name:e.target.value}:g))} className="h-11 min-w-0 flex-1 rounded-xl bg-white/10 px-3 font-bold"/><button disabled={!manageable} onClick={e=>{e.stopPropagation();setDrafts(c=>c.filter(g=>g.id!==group.id));}} className="rounded-xl border border-red-400/20 px-3 text-red-300">삭제</button></div><select disabled={!manageable} value={group.sessionId??""} onChange={e=>setDrafts(c=>c.map(g=>g.id===group.id?{...g,sessionId:e.target.value||null}:g))} className="mt-3 h-11 w-full rounded-xl bg-zinc-900 px-3"><option value="">게임 미정</option>{games.map(game=><option key={game.id} value={game.id}>{game.game?.name??"게임"}</option>)}</select><div className="mt-3 flex flex-wrap gap-2">{group.userIds.map(userId=>{const member=participants.find(item=>item.user_id===userId);return <button key={userId} onClick={e=>{e.stopPropagation();if(manageable)setSelectedUser(userId);}} className="min-h-10 rounded-xl bg-white/[0.05] px-3"><span>{member?label(member):"회원"}</span><span className="ml-2 text-xs text-zinc-500">이동</span></button>;})}{group.userIds.length===0&&<p className="py-4 text-sm text-zinc-600">참가자를 선택해 이동하세요.</p>}</div>{selectedGame&&<div className="mt-4 border-t border-white/10 pt-4"><div className="mb-3 flex items-center justify-between"><p className="font-bold">조별 플레이 기록</p>{manageable&&<button disabled={busy} onClick={e=>{e.stopPropagation();void addGroupRound(group);}} className="min-h-10 rounded-xl bg-amber-400 px-4 font-bold text-zinc-950">+ 한 판 추가</button>}</div><GameCard eventGame={selectedGame} canManage={manageable} onChanged={load}/></div>}</article>;})}</div>
 {manageable&&<div className="mt-6 grid grid-cols-2 gap-3"><button disabled={busy} onClick={reset} className="min-h-12 rounded-xl border border-red-400/30 text-red-300">전체 초기화</button><button disabled={busy||drafts.length===0} onClick={save} className="min-h-12 rounded-xl bg-amber-400 font-bold text-zinc-950">{busy?"저장 중...":"조 편성 저장"}</button></div>}</section>;
}
