"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import type { EventGameRound } from "@/types/event";

type Role={id:string;name:string;team_name:string};
type Props={round:EventGameRound;gameId:string;onClose:()=>void;onSaved:()=>Promise<void>|void};
const playerName=(player:EventGameRound["players"][number])=>player.profile?.activity_name?.trim()||"회원";

export default function RoleResultDialog({round,gameId,onClose,onSaved}:Props){
 const supabase=useMemo(()=>createClient(),[]);const [roles,setRoles]=useState<Role[]>([]);const [search,setSearch]=useState("");const [roleByUser,setRoleByUser]=useState<Record<string,string>>({});const [teamByUser,setTeamByUser]=useState<Record<string,string>>({});const [winningTeam,setWinningTeam]=useState("");const [busy,setBusy]=useState(false);
 useEffect(()=>{setRoleByUser(Object.fromEntries(round.players.map(p=>[p.user_id,p.role_name??""])));setTeamByUser(Object.fromEntries(round.players.map(p=>[p.user_id,p.team_name??""])));const winner=round.players.find(p=>p.is_winner)?.team_name??"";setWinningTeam(winner);void supabase.from("game_roles").select("id,name,team_name").eq("game_id",gameId).order("sort_order").then(({data,error})=>{if(error)console.error("역할 조회 오류",error);else setRoles((data??[]) as Role[]);});},[gameId,round,supabase]);
 function choose(userId:string,role:Role){setRoleByUser(c=>({...c,[userId]:role.name}));setTeamByUser(c=>({...c,[userId]:role.team_name}));}
 async function save(){if(round.players.some(p=>!roleByUser[p.user_id]||!teamByUser[p.user_id])){alert("모든 참가자의 역할과 팀을 선택해 주세요.");return;}if(!winningTeam){alert("승리 팀을 선택해 주세요.");return;}try{setBusy(true);const {error}=await supabase.from("event_round_players").upsert(round.players.map(p=>({round_id:round.id,user_id:p.user_id,role_name:roleByUser[p.user_id],team_name:teamByUser[p.user_id],is_winner:teamByUser[p.user_id]===winningTeam,updated_at:new Date().toISOString()})),{onConflict:"round_id,user_id"});if(error)throw error;await onSaved();onClose();}catch(e){const message=typeof e==="object"&&e&&"message" in e?String(e.message):"역할 결과 저장에 실패했습니다.";console.error(e);alert(message);}finally{setBusy(false);}}
 async function clear(){if(!confirm("역할·팀·승패 결과를 모두 삭제할까요?"))return;try{setBusy(true);const {error}=await supabase.from("event_round_players").update({role_name:null,team_name:null,is_winner:null,updated_at:new Date().toISOString()}).eq("round_id",round.id);if(error)throw error;await onSaved();onClose();}catch(e){const message=typeof e==="object"&&e&&"message" in e?String(e.message):"결과 삭제에 실패했습니다.";alert(message);}finally{setBusy(false);}}
 const teams=[...new Set(roles.map(r=>r.team_name))];const filtered=roles.filter(r=>`${r.name} ${r.team_name}`.toLowerCase().includes(search.toLowerCase()));const hasResult=round.players.some(p=>p.role_name||p.team_name||p.is_winner!==null);
 return <div className="fixed inset-0 z-[100] flex items-end bg-black/70 sm:items-center sm:justify-center"><section className="max-h-[94dvh] w-full overflow-y-auto rounded-t-3xl border border-white/10 bg-zinc-950 p-5 text-white sm:max-w-2xl sm:rounded-3xl sm:p-7"><div className="flex justify-between"><div><p className="text-sm text-amber-300">{round.round_number}판</p><h2 className="text-xl font-bold">역할·팀 결과</h2></div><button onClick={onClose} className="min-h-11 min-w-11 rounded-full bg-white/5 text-xl">×</button></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="역할 또는 팀 검색" className="mt-5 h-12 w-full rounded-xl border border-white/10 bg-zinc-900 px-4"/><div className="mt-4 space-y-4">{round.players.map(player=><div key={player.user_id} className="rounded-2xl border border-white/10 p-4"><p className="font-bold">{playerName(player)}</p><p className="mt-1 text-sm text-amber-300">{roleByUser[player.user_id]||"역할 미선택"} · {teamByUser[player.user_id]||"팀 미선택"}</p><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3">{filtered.map(role=><button key={role.id} onClick={()=>choose(player.user_id,role)} className={`min-h-11 rounded-xl px-2 text-sm ${roleByUser[player.user_id]===role.name?"bg-amber-400 font-bold text-zinc-950":"bg-white/10"}`}>{role.name}<small className="block opacity-70">{role.team_name}</small></button>)}</div></div>)}</div><div className="mt-6"><p className="font-bold">승리 팀</p><div className="mt-2 grid grid-cols-2 gap-2">{teams.map(team=><button key={team} onClick={()=>setWinningTeam(team)} className={`min-h-12 rounded-xl font-bold ${winningTeam===team?"bg-emerald-400 text-zinc-950":"bg-white/10"}`}>{team}</button>)}</div></div><div className="sticky bottom-0 mt-6 grid grid-cols-2 gap-3 bg-zinc-950 pt-3">{hasResult?<button disabled={busy} onClick={clear} className="min-h-12 rounded-xl border border-red-400/30 text-red-300">결과 삭제</button>:<button onClick={onClose} className="min-h-12 rounded-xl border border-white/10">취소</button>}<button disabled={busy} onClick={save} className="min-h-12 rounded-xl bg-amber-400 font-bold text-zinc-950">{busy?"저장 중...":"결과 저장"}</button></div></section></div>;
}
