"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { CLOCKTOWER_CHARACTERS, CLOCKTOWER_DIFFICULTIES } from "@/lib/clocktower/characters";

type Tip={id:string;author_name:string|null;clocktower_difficulty:string|null;character_name:string|null;character_tip:string|null;created_at:string};
type Vote={review_id:string;user_id:string};

export default function ClocktowerCharacterTips({gameId}:{gameId:string}){
 const supabase=useMemo(()=>createClient(),[]);const[tips,setTips]=useState<Tip[]>([]);const[votes,setVotes]=useState<Vote[]>([]);const[userId,setUserId]=useState<string|null>(null);const[difficulty,setDifficulty]=useState("");const[character,setCharacter]=useState("");const[busy,setBusy]=useState<string|null>(null);
 const load=useCallback(async()=>{const[{data:t},{data:{user}}]=await Promise.all([supabase.from("game_reviews").select("id,author_name,clocktower_difficulty,character_name,character_tip,created_at").eq("game_id",gameId).not("character_tip","is",null),supabase.auth.getUser()]);const rows=(t??[]) as Tip[];const ids=rows.map(row=>row.id);const{data:v}=ids.length?await supabase.from("clocktower_tip_votes").select("review_id,user_id").in("review_id",ids):{data:[]};setTips(rows);setVotes((v??[]) as Vote[]);setUserId(user?.id??null)},[gameId,supabase]);
 useEffect(()=>{void load()},[load]);
 const counts=useMemo(()=>{const result=new Map<string,number>();votes.forEach(v=>result.set(v.review_id,(result.get(v.review_id)??0)+1));return result},[votes]);
 const characters=difficulty?CLOCKTOWER_CHARACTERS[difficulty as keyof typeof CLOCKTOWER_CHARACTERS]:[];
 const visible=tips.filter(t=>(!difficulty||t.clocktower_difficulty===difficulty)&&(!character||t.character_name===character)).sort((a,b)=>(counts.get(b.id)??0)-(counts.get(a.id)??0)||new Date(b.created_at).getTime()-new Date(a.created_at).getTime());
 async function toggle(reviewId:string){if(!userId){alert("로그인 후 추천할 수 있습니다.");return}try{setBusy(reviewId);const mine=votes.some(v=>v.review_id===reviewId&&v.user_id===userId);const response=mine?await supabase.from("clocktower_tip_votes").delete().eq("review_id",reviewId).eq("user_id",userId):await supabase.from("clocktower_tip_votes").insert({review_id:reviewId,user_id:userId});if(response.error)throw response.error;await load()}catch(e){alert(e instanceof Error?e.message:"추천을 반영하지 못했습니다.")}finally{setBusy(null)}}
 return <section className="mt-12 rounded-3xl border border-violet-400/20 bg-violet-400/[0.03] p-5 sm:p-7"><p className="text-sm font-semibold tracking-[.2em] text-violet-300">CHARACTER NOTES</p><h2 className="mt-2 text-3xl font-bold">캐릭터 느낌·플레이 팁</h2><p className="mt-3 text-sm text-zinc-500">실제 플레이한 멤버가 남긴 스포일러 없는 팁입니다. 추천이 많은 글부터 표시됩니다.</p>
 <div className="mt-6 grid gap-3 sm:grid-cols-2"><select value={difficulty} onChange={e=>{setDifficulty(e.target.value);setCharacter("")}} className="h-12 rounded-xl border border-white/10 bg-zinc-900 px-4"><option value="">전체 난이도 · 최근 팁</option>{CLOCKTOWER_DIFFICULTIES.map(value=><option key={value}>{value}</option>)}</select><select value={character} disabled={!difficulty||!characters.length} onChange={e=>setCharacter(e.target.value)} className="h-12 rounded-xl border border-white/10 bg-zinc-900 px-4 disabled:opacity-40"><option value="">전체 캐릭터</option>{(["이야기꾼","주민","외지인","하수인","악마"] as const).map(type=><optgroup key={type} label={type}>{characters.filter(c=>c.type===type).map(c=><option key={c.name}>{c.name}</option>)}</optgroup>)}</select></div>
 {visible.length?<div className="mt-6 space-y-3">{visible.map(t=>{const mine=votes.some(v=>v.review_id===t.id&&v.user_id===userId);return <article key={t.id} className="rounded-2xl border border-white/10 bg-black/20 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="rounded-full bg-violet-400/10 px-2.5 py-1 text-xs text-violet-200">{t.clocktower_difficulty}</span><h3 className="mt-2 text-xl font-bold">{t.character_name}</h3><p className="mt-1 text-xs text-zinc-600">{t.author_name?.trim()||"보드라운지 회원"}</p></div><button disabled={busy===t.id} onClick={()=>void toggle(t.id)} className={`rounded-xl border px-4 py-2 text-sm font-bold ${mine?"border-amber-300 bg-amber-400/15 text-amber-200":"border-white/10 text-zinc-300"}`}>👍 추천 {counts.get(t.id)??0}</button></div><p className="mt-4 whitespace-pre-wrap break-words leading-7 text-zinc-300">{t.character_tip}</p></article>})}</div>:<div className="mt-6 rounded-2xl border border-dashed border-white/10 py-12 text-center text-sm text-zinc-600">조건에 맞는 캐릭터 팁이 아직 없습니다.</div>}
 </section>
}
