"use client";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";

type OwnReview={id:string;rating:number;content:string|null};
export default function GameReviewAction({gameId,onSaved}:{gameId:string;onSaved?:()=>void}){
 const supabase=useMemo(()=>createClient(),[]);const[userId,setUserId]=useState<string|null>(null);const[eligible,setEligible]=useState(false);const[review,setReview]=useState<OwnReview|null>(null);const[open,setOpen]=useState(false);const[rating,setRating]=useState(5);const[content,setContent]=useState("");const[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const{data:{user}}=await supabase.auth.getUser();setUserId(user?.id??null);if(!user){setEligible(false);return}const[{data:can},{data:mine}]=await Promise.all([supabase.rpc("can_review_game",{p_game_id:gameId}),supabase.from("game_reviews").select("id,rating,content").eq("game_id",gameId).eq("user_id",user.id).maybeSingle()]);setEligible(Boolean(can));const row=(mine??null) as OwnReview|null;setReview(row);if(row){setRating(row.rating);setContent(row.content??"")}},[gameId,supabase]);
 useEffect(()=>{void load()},[load]);
 async function save(e:FormEvent){e.preventDefault();if(!userId||!eligible)return;try{setBusy(true);const{data:p}=await supabase.from("profiles").select("activity_name").eq("id",userId).maybeSingle();const payload={game_id:gameId,user_id:userId,author_name:p?.activity_name?.trim()||"보드라운지 회원",rating,content:content.trim()||null,updated_at:new Date().toISOString()};const{error}=review?await supabase.from("game_reviews").update(payload).eq("id",review.id):await supabase.from("game_reviews").insert(payload);if(error)throw error;await load();setOpen(false);onSaved?.();window.location.reload()}catch(e){alert(e instanceof Error?e.message:"평가를 저장하지 못했습니다.")}finally{setBusy(false)}}
 if(!userId)return <p className="text-sm text-zinc-600">로그인 후 실제 플레이 기록이 있으면 평가할 수 있습니다.</p>;
 if(!eligible)return <p className="rounded-xl border border-white/10 px-4 py-3 text-sm text-zinc-500">이 게임을 이벤트에서 실제로 플레이한 기록이 있어야 평가할 수 있습니다.</p>;
 return <><button onClick={()=>setOpen(true)} className="inline-flex justify-center rounded-2xl bg-amber-400 px-6 py-3 font-bold text-zinc-950">{review?"내 평가 수정":"이 게임 평가하기"}</button>{open&&<div className="fixed inset-0 z-[120] flex items-end bg-black/75 sm:items-center sm:justify-center" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><form onSubmit={save} className="w-full rounded-t-3xl border border-white/10 bg-zinc-950 p-6 text-white sm:max-w-lg sm:rounded-3xl"><div className="flex justify-between"><div><p className="text-sm text-amber-300">PLAYER REVIEW</p><h2 className="text-2xl font-bold">게임 평가</h2></div><button type="button" onClick={()=>setOpen(false)} className="h-11 w-11 rounded-full bg-white/10">×</button></div><p className="mt-3 text-sm text-zinc-500">이벤트의 실제 판 참가 기록으로 평가 권한이 확인되었습니다.</p><div className="mt-6"><p className="font-bold">별점</p><div className="mt-2 flex gap-2">{[1,2,3,4,5].map(n=><button type="button" key={n} onClick={()=>setRating(n)} className={`text-4xl ${n<=rating?"text-amber-400":"text-zinc-700"}`}>★</button>)}</div></div><textarea value={content} onChange={e=>setContent(e.target.value)} maxLength={500} rows={5} placeholder="플레이 후기를 남겨주세요." className="mt-5 w-full resize-none rounded-xl border border-white/10 bg-zinc-900 p-4"/><button disabled={busy} className="mt-5 h-12 w-full rounded-xl bg-amber-400 font-bold text-zinc-950">{busy?"저장 중...":"평가 저장"}</button></form></div>}</>;
}
