"use client";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {createClient} from "@/lib/supabase/client";

type Combo={kind:string;size:number;strength:number;bomb:boolean};
type Lobby={id:string;title:string;host_name:string;status:string;players:number;mine:boolean;target_score:number;turn_seconds:number};
type Player={user_id:string;seat:number;team:number;name:string;gender:string|null;count:number;ready:boolean;grand_choice:boolean|null;grand_called:boolean;small_called:boolean;finish_order:number|null};
type Room={id:string;title:string;host_id:string;status:string;turn_seat:number|null;lead:Combo|null;trick:{seat:number;cards:number[]}[];last_trick_seat:number|null;winner_team:number|null;target_score:number;turn_seconds:number;turn_deadline:string|null;round_no:number;sky_score:number;pink_score:number;round_history:{round:number;sky:number;pink:number;first_user:string}[];wish_rank:number|null};
type Snap={room:Room;me:{user_id:string;seat:number;team:number;cards:number[];ready:boolean;grand_choice:boolean|null;grand_called:boolean;small_called:boolean;has_played:boolean};players:Player[];exchange_count:number;my_gifts:Record<string,number>;received:{card:number;from_name:string}[]};
type Chat={id:string;user:string;text:string;at:number};
const suits=["●","◆","★","▲"],colors=["text-sky-500","text-pink-500","text-amber-500","text-violet-500"],teams=[{name:"하늘팀",border:"border-sky-400",text:"text-sky-300"},{name:"핑크팀",border:"border-pink-400",text:"text-pink-300"}];
function rank(c:number){return c<52?Math.floor(c/4)+2:c===52?1:c===53?0:c===54?14.5:15}
function label(c:number){if(c===52)return"참새";if(c===53)return"개";if(c===54)return"봉황";if(c===55)return"용";const r=rank(c);return r===14?"A":r===13?"K":r===12?"Q":r===11?"J":String(r)}
function combo(cards:number[]):Combo|null{if(!cards.length||cards.includes(53)&&cards.length>1||cards.includes(55)&&cards.length>1)return null;const ph=cards.includes(54),normal=cards.filter(c=>c<53),rs=normal.map(rank),counts=new Map<number,number>();rs.forEach(v=>counts.set(v,(counts.get(v)||0)+1));const vals=[...counts.keys()].sort((a,b)=>a-b),n=cards.length;if(n===1)return{kind:"single",size:1,strength:rank(cards[0]),bomb:false};if(n===4&&vals.length===1&&!ph)return{kind:"four",size:4,strength:vals[0],bomb:true};if((n===2||n===3)&&vals.length===1&&(counts.get(vals[0])||0)+(ph?1:0)===n)return{kind:n===2?"pair":"triple",size:n,strength:vals[0],bomb:false};if(n===5)for(const a of vals)for(const b of vals)if(a!==b&&(counts.get(a)||0)+(ph?1:0)>=3&&(counts.get(b)||0)>=2)return{kind:"full",size:5,strength:a,bomb:false};if(n>=4&&n%2===0&&!cards.includes(52)){const need=n/2;if(vals.at(-1)!-vals[0]===need-1&&vals.reduce((s,v)=>s+Math.floor((counts.get(v)||0)/2),0)+(ph?0.5:0)>=need)return{kind:"pair-straight",size:n,strength:vals.at(-1)!,bomb:false}}const seq=[...new Set(rs)].sort((a,b)=>a-b);if(n>=5&&seq.length+(ph?1:0)===n&&seq.at(-1)!-seq[0]<=n-1){const bomb=!ph&&cards.every(c=>c<52&&c%4===cards[0]%4);return{kind:bomb?"straight-bomb":"straight",size:n,strength:seq.at(-1)!,bomb}}return null}
function Card({card,onClick,selected=false,tiny=false}:{card:number;onClick?:()=>void;selected?:boolean;tiny?:boolean}){const special=card>=52,pos=card===52?"100% 100%":card===53?"0 100%":card===54?"100% 0":"0 0";return <button type="button" onClick={onClick} className={`relative shrink-0 overflow-hidden rounded-lg border-2 bg-[#fffaf0] shadow-md transition ${tiny?"h-16 w-11":"h-[5.3rem] w-[3.2rem] sm:h-24 sm:w-16"} ${selected?"-translate-y-2 border-amber-400":"border-black/10"}`}><span className={`absolute left-1 top-0.5 z-10 text-[10px] font-black ${special?"text-zinc-800":colors[card%4]}`}>{label(card)} {!special&&suits[card%4]}</span>{special?<span className="absolute inset-x-0.5 bottom-0.5 top-5 bg-[url('/tichu-special-mascots-v1.png')] bg-[length:200%_200%] bg-no-repeat" style={{backgroundPosition:pos}}/>:<span className={`grid h-full place-items-center pt-4 text-xl ${colors[card%4]}`}>{suits[card%4]}</span>}</button>}
function Avatar({p,active=false,mine=false}:{p?:Player;active?:boolean;mine?:boolean}){if(!p)return <div/>;return <div className={`mx-auto w-28 rounded-2xl border-4 bg-zinc-900/95 p-2 text-center shadow-xl transition ${active?`${teams[p.team].border} scale-105 shadow-[0_0_24px_rgba(125,211,252,.4)]`:"border-white/10"}`}><div className={`mx-auto grid h-10 w-10 place-items-center rounded-full text-2xl ${p.gender==="여"?"bg-pink-200":"bg-sky-200"}`}>{p.gender==="여"?"👧":"👦"}</div><p className="mt-1 truncate text-sm font-black">{p.name}{mine?" · 나":""}</p><p className={`text-[10px] font-bold ${teams[p.team].text}`}>{teams[p.team].name} · {p.count}장</p><p className="text-[9px] text-amber-300">{p.grand_called&&"라지 "}{p.small_called&&"스몰 "}{p.finish_order&&`${p.finish_order}등`}</p></div>}

export default function TichuClient(){const supabase=useMemo(()=>createClient(),[]),channel=useRef<ReturnType<typeof supabase.channel>|null>(null);const[user,setUser]=useState<string|null>(null),[rooms,setRooms]=useState<Lobby[]>([]),[roomId,setRoomId]=useState<string|null>(null),[snap,setSnap]=useState<Snap|null>(null),[selected,setSelected]=useState<number[]>([]),[target,setTarget]=useState(1000),[seconds,setSeconds]=useState(15),[left,setLeft]=useState(0),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[wish,setWish]=useState(2),[chatOpen,setChatOpen]=useState(false),[chatText,setChatText]=useState(""),[chats,setChats]=useState<Chat[]>([]);
 const lobby=useCallback(async()=>{const{data}=await supabase.rpc("tichu_lobby");setRooms((data||[])as Lobby[])},[supabase]),load=useCallback(async()=>{if(!roomId)return;const{data,error}=await supabase.rpc("tichu_snapshot",{p_room:roomId});if(!error&&data)setSnap(data as Snap)},[roomId,supabase]);
 const rpc=useCallback(async(name:string,args:Record<string,unknown>={})=>{setBusy(true);setMessage("");const{data,error}=await supabase.rpc(name,args);setBusy(false);if(error){setMessage(error.message);throw error}return data},[supabase]);
 const refresh=useCallback(()=>{void channel.current?.send({type:"broadcast",event:"refresh",payload:{}})},[]),act=useCallback(async(name:string,args:Record<string,unknown>)=>{try{await rpc(name,args);setSelected([]);await load();await lobby();refresh()}catch{}},[load,lobby,refresh,rpc]);
 useEffect(()=>{void supabase.auth.getUser().then(({data})=>setUser(data.user?.id||null));void lobby()},[lobby,supabase]);useEffect(()=>{const i=setInterval(()=>void(roomId?load():lobby()),roomId?2000:4000);return()=>clearInterval(i)},[load,lobby,roomId]);
 useEffect(()=>{if(!roomId)return;const c=supabase.channel(`tichu:${roomId}`,{config:{broadcast:{self:false}}});c.on("broadcast",{event:"refresh"},()=>void load()).on("broadcast",{event:"chat"},({payload})=>setChats(x=>[...x.slice(-99),payload as Chat])).subscribe();channel.current=c;return()=>{channel.current=null;void supabase.removeChannel(c)}},[load,roomId,supabase]);
 useEffect(()=>{const tick=()=>{if(!snap?.room.turn_deadline)return setLeft(0);const n=Math.max(0,Math.ceil((new Date(snap.room.turn_deadline).getTime()-Date.now())/1000));setLeft(n);if(!n&&roomId&&snap.room.status==="PLAYING")void act("tichu_timeout",{p_room:roomId})};tick();const i=setInterval(tick,1000);return()=>clearInterval(i)},[act,roomId,snap?.room.status,snap?.room.turn_deadline]);
 async function create(){try{setRoomId(await rpc("tichu_create_room",{p_title:null,p_target_score:target,p_turn_seconds:seconds})as string)}catch{}}async function join(id:string){try{setRoomId(await rpc("tichu_join_room",{p_room:id})as string)}catch{}}async function leave(){if(!roomId)return;try{await rpc("tichu_leave_room",{p_room:roomId});refresh();setRoomId(null);setSnap(null);await lobby()}catch{}}
 function send(){const text=chatText.trim().slice(0,200),me=snap?.players.find(p=>p.user_id===user);if(!text||!me)return;const x={id:crypto.randomUUID(),user:me.name,text,at:Date.now()};setChats(v=>[...v.slice(-99),x]);void channel.current?.send({type:"broadcast",event:"chat",payload:x});setChatText("")}
 if(!user)return <main className="p-20 text-center"><h1 className="text-4xl font-black">티츄</h1><p className="mt-4 text-zinc-400">로그인한 멤버만 플레이할 수 있습니다.</p></main>;
 if(!roomId)return <main className="mx-auto max-w-5xl px-4 py-10"><div className="flex items-end justify-between"><div><p className="text-sm font-bold tracking-[.3em] text-sky-300">WAWEDO TICHU</p><h1 className="mt-2 text-4xl font-black">티츄 놀이터</h1><p className="mt-2 text-zinc-400">방을 누르면 코드 없이 바로 참여합니다.</p></div><span className="rounded-xl border border-white/10 p-2 text-sm">👧 👦 기본 아바타</span></div><section className="mt-7 grid gap-3 rounded-3xl border border-sky-300/20 bg-sky-300/5 p-5 sm:grid-cols-[1fr_1fr_auto]"><label className="text-sm text-zinc-400">목표 점수<input type="number" value={target} onChange={e=>setTarget(Number(e.target.value))} className="mt-1 w-full rounded-xl bg-zinc-900 p-3 text-white"/></label><label className="text-sm text-zinc-400">턴 제한 초<input type="number" value={seconds} onChange={e=>setSeconds(Number(e.target.value))} className="mt-1 w-full rounded-xl bg-zinc-900 p-3 text-white"/></label><button disabled={busy} onClick={()=>void create()} className="self-end rounded-xl bg-sky-300 px-6 py-3 font-black text-black">내 방 만들기</button></section>{message&&<p className="mt-3 text-red-300">{message}</p>}<div className="mt-7 grid gap-3">{rooms.map(r=><button key={r.id} onClick={()=>r.mine?setRoomId(r.id):void join(r.id)} className={`flex items-center justify-between rounded-2xl border p-5 ${r.mine?"border-sky-300/50 bg-sky-300/10":"border-white/10"}`}><span><b className="text-lg">{r.host_name} 방</b><small className="ml-2 text-zinc-500">{r.target_score}점 · {r.turn_seconds}초</small></span><span className="text-sky-300">{r.players}/4 · {r.mine?"복귀":"참여"}</span></button>)}</div></main>;
 if(!snap)return <main className="p-20 text-center">방을 불러오는 중…</main>;
 const{room,me,players}=snap,mine=players.find(p=>p.user_id===me.user_id)!,partner=players.find(p=>p.team===me.team&&p.user_id!==me.user_id),opps=players.filter(p=>p.team!==me.team).sort((a,b)=>a.seat-b.seat),myTurn=room.turn_seat===me.seat,picked=combo(selected),leader=players.find(p=>p.seat===room.last_trick_seat),waiting=room.status==="WAITING",grand=room.status==="GRAND",exchange=room.status==="EXCHANGE",playing=room.status==="PLAYING",roundEnd=room.status==="ROUND_END",host=room.host_id===me.user_id,allReady=players.length===4&&players.every(p=>p.ready),teamsOk=players.filter(p=>p.team===0).length===2&&players.filter(p=>p.team===1).length===2;
 async function play(){if(!roomId||!picked)return;if(leader?.team===me.team&&leader.user_id!==me.user_id&&!confirm("현재 우리 팀이 리드입니다. 그래도 내시겠습니까?\n취소하면 패스합니다."))return void act("tichu_pass",{p_room:roomId});const dragon=selected.includes(55)?opps[Math.max(0,Number(prompt(opps.map((p,i)=>`${i+1}. ${p.name}`).join("\n"),"1"))-1)]?.user_id:null,playCombo=selected.length===1&&selected[0]===54?{...picked,strength:room.lead?.kind==="single"?Math.min(14.5,room.lead.strength+.5):1.5}:picked;await act("tichu_play",{p_room:roomId,p_cards:selected,p_combo:playCombo,p_wish:selected.includes(52)?wish:null,p_dragon_target:dragon})}
 return <main className="mx-auto max-w-5xl px-2 py-4 sm:px-5"><header className="sticky top-0 z-20 rounded-2xl border border-white/10 bg-zinc-950/95 p-3"><div className="flex justify-between"><div><p className="text-xs text-zinc-500">{room.round_no}라운드 · {room.status}</p><b>{room.title}</b></div><div className="flex gap-2"><button onClick={()=>setChatOpen(true)} className="rounded-xl border border-white/10 p-2">💬</button>{waiting&&<button onClick={()=>void leave()} className="rounded-xl border border-red-400/30 px-3 text-xs text-red-300">나가기</button>}</div></div><div className="mt-2 grid grid-cols-[1fr_auto_1fr] text-center"><b className="text-sky-300">하늘팀 {room.sky_score}</b><span className={`rounded-full px-3 py-1 ${left<=5&&playing?"bg-red-500":"bg-white/10"}`}>{playing?`${left}초`:`${room.target_score}점`}</span><b className="text-pink-300">{room.pink_score} 핑크팀</b></div></header>
 {waiting&&<section className="mt-4 rounded-3xl border border-white/10 p-5"><h2 className="text-xl font-black">팀 선택 및 준비</h2><div className="mt-4 grid grid-cols-2 gap-3">{[0,1].map(t=><button key={t} onClick={()=>void act("tichu_set_team",{p_room:roomId,p_team:t})} className={`rounded-2xl border-2 p-4 font-black ${me.team===t?`${teams[t].border} ${teams[t].text}`:"border-white/10"}`}>{teams[t].name} {players.filter(p=>p.team===t).length}/2</button>)}</div><div className="mt-4 grid gap-2 sm:grid-cols-2">{players.map(p=><div key={p.user_id} className={`flex justify-between rounded-xl border p-3 ${teams[p.team].border}`}><span>{p.name} <small className={p.ready?"text-emerald-300":"text-zinc-600"}>{p.ready?"READY":"대기"}</small></span>{host&&p.user_id!==me.user_id&&<button onClick={()=>void act("tichu_kick",{p_room:roomId,p_user:p.user_id})} className="text-xs text-red-300">강퇴</button>}</div>)}</div><button onClick={()=>void act("tichu_toggle_ready",{p_room:roomId})} className={`mt-4 w-full rounded-xl p-3 font-black ${me.ready?"bg-emerald-400 text-black":"bg-white/10"}`}>{me.ready?"준비 완료!":"준비하기"}</button>{host&&<button disabled={!allReady||!teamsOk} onClick={()=>void act("tichu_start_room",{p_room:roomId})} className="mt-2 w-full rounded-xl bg-amber-300 p-3 font-black text-black disabled:opacity-30">게임 시작</button>}</section>}
 {grand&&<section className="mt-4 rounded-3xl border border-amber-300/30 p-6 text-center"><h2 className="text-2xl font-black">8장 확인 · 라지 티츄</h2>{me.grand_choice===null?<div className="mt-4 grid grid-cols-2 gap-3"><button onClick={()=>void act("tichu_grand_choice",{p_room:roomId,p_call:true})} className="rounded-xl bg-amber-300 p-3 font-black text-black">라지 티츄!</button><button onClick={()=>void act("tichu_grand_choice",{p_room:roomId,p_call:false})} className="rounded-xl border border-white/15">선언 안 함</button></div>:<p className="mt-3 text-emerald-300">선택 완료</p>}</section>}
 {(grand||exchange||playing)&&<section className="relative mt-4 min-h-[25rem] rounded-[2rem] border border-white/10 bg-[radial-gradient(circle_at_center,#18342d,#09090b_72%)]"><div className="absolute left-1/2 top-3 -translate-x-1/2"><Avatar p={partner} active={room.turn_seat===partner?.seat}/></div><div className="absolute left-2 top-1/2 -translate-y-1/2"><Avatar p={opps[0]} active={room.turn_seat===opps[0]?.seat}/></div><div className="absolute right-2 top-1/2 -translate-y-1/2"><Avatar p={opps[1]} active={room.turn_seat===opps[1]?.seat}/></div><div className="absolute bottom-3 left-1/2 -translate-x-1/2"><Avatar p={mine} active={myTurn} mine/></div><div className="absolute left-1/2 top-1/2 flex max-w-[40%] -translate-x-1/2 -translate-y-1/2 justify-center -space-x-5">{(room.trick.at(-1)?.cards||[]).map(c=><Card key={c} card={c} tiny/>)}</div></section>}
 {exchange&&<section className="mt-4 rounded-3xl border border-white/10 p-4"><div className="flex justify-between"><div><b>카드 한 장 선택 → 받을 멤버 선택</b><p className="text-xs text-zinc-500">각 멤버에게 한 장씩 · 완료 {snap.exchange_count}/4</p></div>{!me.small_called&&<button onClick={()=>void act("tichu_declare_small",{p_room:roomId})} className="text-violet-300">스몰 티츄</button>}</div><div className="mt-3 grid grid-cols-3 gap-2">{players.filter(p=>p.user_id!==me.user_id).map(p=><button key={p.user_id} disabled={selected.length!==1||snap.my_gifts[p.user_id]!=null} onClick={()=>void act("tichu_give_card",{p_room:roomId,p_target:p.user_id,p_card:selected[0]})} className={`rounded-xl border p-2 disabled:opacity-30 ${teams[p.team].border}`}>{p.name}{snap.my_gifts[p.user_id]!=null&&" ✓"}</button>)}</div></section>}
 {playing&&<section className="mt-4 text-center"><div className="flex flex-wrap justify-center gap-2"><button disabled={(!myTurn&&!picked?.bomb)||!picked||busy} onClick={()=>void play()} className="rounded-xl bg-amber-300 px-6 py-3 font-black text-black disabled:opacity-30">{!myTurn&&picked?.bomb?"폭탄 내기":"카드 내기"}</button><button disabled={!myTurn||!room.lead||busy} onClick={()=>void act("tichu_pass",{p_room:roomId})} className="rounded-xl border px-6 py-3 disabled:opacity-30">패스</button>{!me.has_played&&!me.small_called&&<button onClick={()=>void act("tichu_declare_small",{p_room:roomId})} className="rounded-xl bg-violet-500/20 px-4 text-violet-300">스몰 티츄</button>}{selected.includes(52)&&<select value={wish} onChange={e=>setWish(Number(e.target.value))} className="rounded-xl bg-zinc-900 p-3">{Array.from({length:13},(_,i)=>i+2).map(n=><option key={n} value={n}>소원 {n===14?"A":n}</option>)}</select>}</div>{room.wish_rank&&<p className="mt-2 text-amber-300">소원: {room.wish_rank===14?"A":room.wish_rank}</p>}</section>}
 {(grand||exchange||playing)&&<section className="mt-4 rounded-3xl border border-white/10 bg-zinc-950 p-3"><div className="grid grid-flow-col grid-rows-2 justify-center gap-1.5 py-3">{[...me.cards].sort((a,b)=>rank(a)-rank(b)||a-b).map(c=><Card key={c} card={c} selected={selected.includes(c)} onClick={()=>setSelected(s=>s.includes(c)?s.filter(x=>x!==c):[...s,c])}/>)}</div>{picked&&<p className="text-center text-xs text-sky-300">{picked.kind} · {picked.size}장</p>}{snap.received.length>0&&!exchange&&<p className="mt-2 text-center text-xs text-zinc-500">{snap.received.map(x=>`${x.from_name} → ${label(x.card)}`).join(" · ")}</p>}</section>}
 {roundEnd&&<section className="mt-4 rounded-3xl border p-6 text-center"><h2 className="text-2xl font-black">{room.round_no}라운드 종료</h2><Score room={room}/><button onClick={()=>void act("tichu_toggle_ready",{p_room:roomId})} className={`mt-4 rounded-xl px-6 py-3 ${me.ready?"bg-emerald-400 text-black":"bg-white/10"}`}>{me.ready?"준비 완료":"다음 라운드 준비"}</button>{host&&<button disabled={!allReady} onClick={()=>void act("tichu_start_room",{p_room:roomId})} className="ml-2 rounded-xl bg-amber-300 px-6 py-3 text-black disabled:opacity-30">다음 라운드</button>}</section>}
 {room.status==="FINISHED"&&<section className="mt-4 rounded-3xl border border-amber-300/30 p-8 text-center"><h2 className="text-3xl font-black">{teams[room.winner_team||0].name} 승리!</h2><Score room={room}/></section>}{message&&<p className="mt-4 rounded-xl bg-red-500/10 p-3 text-center text-red-300">{message}</p>}
 {chatOpen&&<div className="fixed inset-0 z-50 bg-black/60" onClick={()=>setChatOpen(false)}><aside className="ml-auto flex h-full w-[min(90vw,24rem)] flex-col bg-zinc-950 p-4" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><h2 className="text-xl font-black">실시간 채팅</h2><button onClick={()=>setChatOpen(false)}>✕</button></div><p className="text-xs text-zinc-500">저장되지 않으며 방이 닫히면 사라집니다.</p><div className="mt-4 flex-1 space-y-2 overflow-y-auto">{chats.map(c=><div key={c.id} className="rounded-xl bg-white/5 p-3"><b className="text-sky-300">{c.user}</b><p>{c.text}</p></div>)}</div><div className="flex gap-2"><input value={chatText} onChange={e=>setChatText(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} className="min-w-0 flex-1 rounded-xl bg-zinc-900 p-3"/><button onClick={send} className="rounded-xl bg-sky-300 px-4 text-black">전송</button></div></aside></div>}</main>}
function Score({room}:{room:Room}){return <div className="mx-auto mt-4 max-w-sm space-y-2">{room.round_history.map(h=><div key={h.round} className="grid grid-cols-3 rounded-xl bg-white/[.04] p-3"><span>{h.round}R</span><b className="text-sky-300">{h.sky}</b><b className="text-pink-300">{h.pink}</b></div>)}<div className="grid grid-cols-3 p-3 font-black"><span>합계</span><span className="text-sky-300">{room.sky_score}</span><span className="text-pink-300">{room.pink_score}</span></div></div>}
